using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorAspectFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class AspectPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG112", "Invalid aspect publication input", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG113", "Aspect publication awaits Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor =>
                System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            if (compilation.Options.MetadataImportOptions != MetadataImportOptions.All)
                compilation = compilation.WithOptions(compilation.Options.WithMetadataImportOptions(MetadataImportOptions.All));
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                    reason + " in " + file.Path + ". No aspect fragment was published; regenerate inputs and wait for compilation."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) ||
                    document.Owner != compilation.AssemblyName || document.Editor != editor) { Fail("Invalid or duplicate aspect fragment"); continue; }
                var source = new StringBuilder("// <auto-generated/>\n");
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    var resolver = new InputManifestTypes(compilation, output.CancellationToken);
                    var callbacks = new List<string>();
                    var constructors = new List<string>();
                    var bodies = new StringBuilder();
                    var valid = true;
                    foreach (var entry in document.Entries) {
                        output.CancellationToken.ThrowIfCancellationRequested();
                        var type = resolver.ResolveDefinition(entry.Value, out var gap);
                        if (type == null || !type.IsUnmanagedType || type.IsRefLikeType || MethodSummaryType.From(type).IsOpen ||
                            !compilation.IsSymbolAccessibleWithin(type, compilation.Assembly) ||
                            !type.AllInterfaces.Any(contract => contract.ToDisplayString() == "ME.BECS.IAspect") ||
                            !BecsCatalogGenerator.TryResolveAspect(type, compilation, out var query, out var construct)) {
                            Fail("Cannot publish " + entry.Value + " (" + (gap ?? "requires supported aspect query/construction; private data fields and their owners must be partial") + ")");
                            valid = false; break;
                        }
                        var method = "Register_" + entry.Key.ToString(CultureInfo.InvariantCulture);
                        callbacks.Add(method);
                        constructors.Add(construct ?? "null");
                        bodies.Append("private static void ").Append(method).Append("() { global::ME.BECS.AspectTypeInfo<")
                            .Append(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">.Validate();\n")
                            .Append(query).Append("(); }\n");
                    }
                    if (!valid) continue;
                    source.Append("namespace ME.BECS.SourceGenerated {\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static class AspectFragment_")
                        .Append(editor ? "Editor" : "Runtime").Append(" {\nprivate static readonly int[] Ordinals = new int[] { ")
                        .Append(string.Join(",", document.Entries.Select(entry => entry.Key.ToString(CultureInfo.InvariantCulture)))).Append(" };\n")
                        .Append("private static readonly global::System.Action[] Callbacks = new global::System.Action[] {\n")
                        .Append(string.Join(",\n", callbacks)).Append("\n};\n")
                        .Append("private static readonly global::ME.BECS.WorldStaticCallbacks.CallbackDelegate<global::ME.BECS.World>[] Constructors = new global::ME.BECS.WorldStaticCallbacks.CallbackDelegate<global::ME.BECS.World>[] {\n")
                        .Append(string.Join(",\n", constructors)).Append("\n};\n").Append(bodies)
                        .Append(editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                            "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
                        .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() => global::ME.BECS.BootstrapRuntime.InstallAspectFragment(")
                        .Append(SymbolDisplay.FormatLiteral(document.Plan, true)).Append(", ")
                        .Append(SymbolDisplay.FormatLiteral(document.Owner, true)).Append(", ").Append(document.Count.ToString(CultureInfo.InvariantCulture))
                        .Append(", Ordinals, Callbacks, Constructors, editor: ").Append(editor ? "true" : "false").Append(");\n} }\n");
                }
                output.AddSource("ME.BECS.AspectFragment." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
