using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// Discovery is per compilation. This generator never assigns IDs or runs initialization.
[Generator(LanguageNames.CSharp)]
public sealed class BecsCatalogGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax declaration && declaration.BaseList != null,
            static (syntax, cancellation) => Describe(syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol))
            .Where(static candidate => candidate != null);
        context.RegisterSourceOutput(candidates.Collect().Combine(context.CompilationProvider.Select(
            static (compilation, _) => compilation.AssemblyName ?? string.Empty)),
            static (production, input) => Emit(production, input.Left, input.Right));
    }

    private static Candidate? Describe(INamedTypeSymbol? type) {
        if (type == null || type.TypeKind != TypeKind.Struct || !type.IsUnmanagedType || type.IsRefLikeType) return null;
        // Match the public discovery surface of the existing editor generator.
        for (var owner = type; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public || owner.Arity != 0) return null;
        }
        var component = type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.IComponent");
        var aspect = type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.IAspect");
        if (!component && !aspect) return null;
        // Shared/static registration and config initialization still belong to the legacy generator.
        var special = type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.IComponentShared" ||
            i.ToDisplayString() == "ME.BECS.IConfigComponentStatic");
        var hasFields = type.GetMembers().OfType<IFieldSymbol>().Any(static field => !field.IsStatic);
        var explicitSize = 0;
        foreach (var attribute in type.GetAttributes()) {
            if (attribute.AttributeClass?.ToDisplayString() != "System.Runtime.InteropServices.StructLayoutAttribute") continue;
            foreach (var argument in attribute.NamedArguments) {
                if (argument.Key == "Size" && argument.Value.Value is int size) explicitSize = size;
            }
        }
        var tag = !hasFields && explicitSize <= 1;
        var defaultProperty = type.GetMembers("Default").OfType<IPropertySymbol>().FirstOrDefault(property =>
            property.IsStatic && property.DeclaredAccessibility == Accessibility.Public && property.GetMethod != null &&
            property.GetMethod.DeclaredAccessibility == Accessibility.Public &&
            SymbolEqualityComparer.Default.Equals(property.Type, type));
        return new Candidate(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), component, aspect,
            component && !special, tag, !tag && defaultProperty != null);
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<Candidate?> input, string assembly) {
        var types = input.Where(static t => t != null).Select(static t => t!).GroupBy(static t => t.Name, StringComparer.Ordinal)
            .Select(static group => group.First()).OrderBy(static t => t.Name, StringComparer.Ordinal).ToArray();
        if (types.Length == 0) return;
        var source = new StringBuilder("// <auto-generated/>\nnamespace ME.BECS.SourceGenerated {\n");
        // A reversible encoding prevents class-name collisions between different asmdefs.
        source.Append("public static class Catalog_").Append(Encode(assembly)).Append(" {\n");
        source.Append("public static global::System.Type[] GetComponents() => new global::System.Type[] {\n");
        foreach (var type in types.Where(static t => t.Component)) source.Append("typeof(").Append(type.Name).Append("),\n");
        source.Append("};\npublic static global::System.Type[] GetAspects() => new global::System.Type[] {\n");
        foreach (var type in types.Where(static t => t.Aspect)) source.Append("typeof(").Append(type.Name).Append("),\n");
        source.Append("};\n");
        foreach (var type in types.Where(static t => t.CanRegister)) {
            context.CancellationToken.ThrowIfCancellationRequested();
            source.Append("// Called individually by the future global bootstrap, in its existing order.\n")
                .Append("public static void Register_").Append(Encode(type.Name)).Append("() {\n")
                .Append("global::ME.BECS.StaticTypes<").Append(type.Name).Append(">.Validate(isTag: ")
                .Append(type.Tag ? "true" : "false").Append(", isStatic: false);\n");
            if (type.HasDefault) source.Append("global::ME.BECS.StaticTypes<").Append(type.Name)
                .Append(">.SetDefaultValue(").Append(type.Name).Append(".Default);\n");
            source.Append("}\n");
        }
        source.Append("}\n}\n");
        context.AddSource("ME.BECS.Catalog.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string Encode(string value) {
        var result = new StringBuilder(value.Length * 4);
        foreach (var character in value) result.Append(((int)character).ToString("X4", System.Globalization.CultureInfo.InvariantCulture));
        return result.ToString();
    }

    private sealed class Candidate : IEquatable<Candidate> {
        public readonly string Name;
        public readonly bool Component, Aspect, CanRegister, Tag, HasDefault;
        public Candidate(string name, bool component, bool aspect, bool canRegister, bool tag, bool hasDefault) {
            Name = name; Component = component; Aspect = aspect; CanRegister = canRegister; Tag = tag; HasDefault = hasDefault;
        }
        public bool Equals(Candidate? other) => other != null && Name == other.Name && Component == other.Component &&
            Aspect == other.Aspect && CanRegister == other.CanRegister && Tag == other.Tag && HasDefault == other.HasDefault;
        public override bool Equals(object? other) => other is Candidate candidate && Equals(candidate);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Name);
    }
}
