using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// During migration only registration payloads remain in the Editor template.
// Emit against the new hooks, so assemblies using the previous template can still
// compile before the user regenerates inputs; never create a second Load method.
[Generator(LanguageNames.CSharp)]
public sealed class BootstrapGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) => {
            var editor = compilation.AssemblyName == "ME.BECS.Gen.Editor";
            if (!editor && compilation.AssemblyName != "ME.BECS.Gen.Runtime") return;
            var ns = editor ? "ME.BECS.Editor" : "ME.BECS";
            if (!HasHook(compilation, ns + ".StaticTypesInitializer", "RegisterGeneratedTypes") ||
                !HasHook(compilation, ns + ".StaticMethods", "RegisterGeneratedMethods")) return;
            var source = new StringBuilder("// <auto-generated/>\nnamespace " + ns + " {\n");
            source.AppendLine("public static unsafe partial class StaticTypesInitializer {");
            source.AppendLine("[global::UnityEngine.Scripting.PreserveAttribute] public static void Load() {");
            source.AppendLine("global::ME.BECS.JobUtils.Initialize();");
            source.AppendLine("RegisterGeneratedTypes();");
            source.AppendLine("global::ME.BECS.LocksCache.Initialize(global::ME.BECS.LocksCache.COMPONENTS, global::ME.BECS.StaticTypes.counter + 1u);");
            source.AppendLine("global::ME.BECS.LocksCache.Initialize(global::ME.BECS.LocksCache.ENT_GROUPS, global::ME.BECS.EntityTypes.groupsCount + 1u);");
            source.AppendLine("} }");
            source.AppendLine("public static unsafe partial class StaticMethods {");
            source.AppendLine("[global::UnityEngine.Scripting.PreserveAttribute]");
            if (!editor) source.AppendLine("[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
            source.AppendLine("public static void Load() {");
            if (!editor) source.AppendLine("global::ME.BECS.Logger.Core.Log(\"[ ME.BECS ] Loading...\");");
            source.AppendLine("global::ME.BECS.LeakDetector.ClearAllocated();");
            if (editor) source.AppendLine("global::ME.BECS.StaticTypes.Dispose();");
            source.AppendLine("global::ME.BECS.Worlds.Initialize();");
            source.AppendLine("global::ME.BECS.SystemsStatic.Initialize();");
            source.AppendLine("StaticTypesInitializer.Load();");
            source.AppendLine("global::ME.BECS.GlobalEvents.Initialize();");
            source.AppendLine("global::ME.BECS.CustomModules.InvokeResetPass();");
            source.AppendLine("RegisterGeneratedMethods();");
            source.AppendLine("global::ME.BECS.EntityConfigRegistry.Initialize();");
            source.AppendLine(editor ? "global::ME.BECS.EntityConfigsRegistry.Initialize(true);" : "global::ME.BECS.EntityConfigsRegistry.Initialize();");
            source.AppendLine("global::ME.BECS.CustomModules.InvokeFirstPass();");
            source.AppendLine("global::ME.BECS.CustomModules.InvokeSecondPass();");
            if (!editor) source.AppendLine("global::ME.BECS.Logger.Core.Log(\"[ ME.BECS ] Loaded\");");
            source.AppendLine("} } }");
            output.AddSource("ME.BECS.Bootstrap.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }

    private static bool HasHook(Compilation compilation, string name, string hook) {
        var type = compilation.Assembly.GetTypeByMetadataName(name);
        return type != null && type.IsStatic && type.DeclaringSyntaxReferences.Length > 0 &&
            type.DeclaringSyntaxReferences.All(reference => reference.GetSyntax() is ClassDeclarationSyntax declaration &&
                declaration.Modifiers.Any(token => token.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword))) &&
            !type.GetMembers("Load").Any() &&
            type.GetMembers(hook).OfType<IMethodSymbol>().Any(method => method.IsStatic && method.ReturnsVoid &&
                method.Parameters.Length == 0 && method.Arity == 0);
    }
}
