using System;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorBootstrapFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class BootstrapPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG130", "Invalid bootstrap publication", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG131", "Bootstrap publication awaits Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor => System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new System.Collections.Generic.HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None, reason + " in " + file.Path + ". No bootstrap plan was published."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) || document.Editor != editor || document.Owner != compilation.AssemblyName) {
                    Fail("Invalid or duplicate bootstrap composition input"); continue;
                }
                var source = new StringBuilder("// <auto-generated/>\n[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    Format.TryEntry(document.Entries[0].Value, editor, out var profile);
                    var network = profile.Selections.Any(item => item.Kind == "Network");
                    var views = profile.Initialize.Contains("views");
                    if (compilation.GetTypeByMetadataName("ME.BECS.BootstrapRuntime") == null ||
                        network && compilation.GetTypeByMetadataName("ME.BECS.Network.BootstrapNetworkMethods") == null ||
                        views && compilation.GetTypeByMetadataName("ME.BECS.Views.BootstrapViews") == null) {
                        Fail("Bootstrap owner is missing framework/addon references"); continue;
                    }
                    BootstrapPhaseInputEmitter.Append(source, document.Owner, editor, profile.Initialize, profile.Register, profile.Jobs, network, views);
                    source.Append("namespace ME.BECS.SourceGenerated { [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static class BootstrapProfile_")
                        .Append(editor ? "Editor" : "Runtime").Append(" {\n")
                        .Append(editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                            "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
                        .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() {\n");
                    foreach (var selection in profile.Selections) {
                        source.Append(selection.Kind == "Network" ? "global::ME.BECS.Network.BootstrapNetworkMethods.ExpectPlan(" :
                            "global::ME.BECS.BootstrapRuntime.Expect" + selection.Kind + "Plan(")
                            .Append(SymbolDisplay.FormatLiteral(selection.Plan, true)).Append(", ")
                            .Append(string.Join(", ", selection.Counts.Select(count => count.ToString(CultureInfo.InvariantCulture))));
                        if (selection.Kind != "Graph") source.Append(", editor: ").Append(editor ? "true" : "false");
                        source.Append(");\n");
                    }
                    source.Append("BootstrapPhaseInputs.Publish();\n}\n");
                    if (!editor) source.Append("[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSplashScreen)]\n")
                        .Append("private static void PublishGraphPass() => global::ME.BECS.CustomModules.RegisterFirstPass(global::ME.BECS.BootstrapRuntime.RegisterInstalledGraphs);\n");
                    source.Append("} }\n");
                }
                output.AddSource("ME.BECS.BootstrapFragment." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
