using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// Definitions own typed registration/AOT bodies. No initializer runs here, and
// no IDs are assigned in syntax, assembly or module-load enumeration order.
[Generator(LanguageNames.CSharp)]
public sealed class ComponentRegistrationGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var methods = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax declaration && declaration.BaseList != null,
            static (syntax, cancellation) => Describe(syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol))
            .Where(static declaration => declaration != null).Collect();
        context.RegisterSourceOutput(methods.Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? "")),
            static (output, input) => {
                var declarations = input.Left.Where(static item => item != null).Distinct(StringComparer.Ordinal)
                    .OrderBy(static item => item, StringComparer.Ordinal).ToArray();
                if (declarations.Length == 0) return;
                var source = "// <auto-generated/>\n#nullable enable\nnamespace ME.BECS.SourceGenerated {\n" +
                    "[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\npublic static class " + OwnerName(input.Right) + " {\n" +
                    string.Join("\n", declarations) + "\n} }\n";
                output.AddSource("ME.BECS.ComponentRegistrations.g.cs", SourceText.From(source, Encoding.UTF8));
            });
    }

    private static string OwnerName(string assembly) => "ComponentRegistrations_" + ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(assembly);

    private static INamedTypeSymbol[] Owners(INamedTypeSymbol type) {
        var owners = new Stack<INamedTypeSymbol>();
        for (var owner = type; owner != null; owner = owner.ContainingType) owners.Push(owner);
        return owners.ToArray();
    }

    private static string Key(INamedTypeSymbol type) => ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(
        (type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString() + ".") +
        string.Join("+", Owners(type).Select(static owner => owner.MetadataName)));

    private static string? Describe(INamedTypeSymbol? type) {
        if (type == null || type.TypeKind != TypeKind.Struct || type.IsRefLikeType || !type.IsUnmanagedType ||
            !type.AllInterfaces.Any(static contract => contract.ToDisplayString() == "ME.BECS.IComponentBase") ||
            Owners(type).Any(static owner => owner.DeclaredAccessibility != Accessibility.Public)) return null;
        var flags = ComponentRegistrationFlags.Get(type, ComponentLayoutReader.IsSourceTag(type));
        // An unused invalid Default must not break its owner assembly; selection
        // still reports the precise invalid contract in the input consumer.
        if ((flags & 1) == 0 && ComponentRegistrationFlags.HasInvalidDefault(type)) return null;
        var parameters = Owners(type).SelectMany(static owner => owner.TypeParameters).ToArray();
        var names = new Dictionary<ITypeParameterSymbol, string>(SymbolEqualityComparer.Default);
        for (var index = 0; index < parameters.Length; ++index) names.Add(parameters[index], "__T" + index);
        string Name(ITypeSymbol symbol) => string.Concat(symbol.ToDisplayParts(SymbolDisplayFormat.FullyQualifiedFormat).Select(part =>
            part.Symbol is ITypeParameterSymbol parameter && names.TryGetValue(parameter, out var name) ? name : part.ToString()));
        var suffix = parameters.Length == 0 ? "" : "<" + string.Join(", ", parameters.Select(parameter => names[parameter])) + ">";
        var constraints = new StringBuilder();
        foreach (var parameter in parameters) {
            var items = new List<string>();
            if (parameter.HasUnmanagedTypeConstraint) items.Add("unmanaged");
            else if (parameter.HasValueTypeConstraint) items.Add("struct");
            else if (parameter.HasReferenceTypeConstraint) items.Add(parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
            else if (parameter.HasNotNullConstraint) items.Add("notnull");
            items.AddRange(parameter.ConstraintTypes.Select(Name));
            if (parameter.HasConstructorConstraint && !parameter.HasValueTypeConstraint && !parameter.HasUnmanagedTypeConstraint) items.Add("new()");
            if (items.Count != 0) constraints.Append(" where ").Append(names[parameter]).Append(" : ").Append(string.Join(", ", items));
        }
        var key = Key(type);
        var source = new StringBuilder("public const int Flags_").Append(key).Append(" = ").Append(flags).AppendLine(";");
        ComponentRegistrationEmitter.Append(source, Name(type), flags, key, suffix, constraints.ToString());
        return source.ToString();
    }

    internal static bool TryResolve(INamedTypeSymbol type, int flags, Compilation compilation, out string? ownerName,
        out string key, out string arguments) {
        ownerName = null;
        key = Key(type.OriginalDefinition);
        var args = Owners(type).SelectMany(static owner => owner.TypeArguments).ToArray();
        arguments = args.Length == 0 ? "" : "<" + string.Join(", ", args.Select(static argument => argument.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) + ">";
        var metadataName = "ME.BECS.SourceGenerated." + OwnerName(type.ContainingAssembly.Name);
        if (SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, compilation.Assembly)) {
            // Other generator outputs are not visible in this compilation. Use the
            // same source eligibility rule as emission, never a speculative lookup.
            if (Describe(type.OriginalDefinition) == null ||
                ComponentRegistrationFlags.Get(type.OriginalDefinition, ComponentLayoutReader.IsSourceTag(type.OriginalDefinition)) != flags) return false;
        } else {
            var owner = type.ContainingAssembly.GetTypeByMetadataName(metadataName);
            if (owner == null || !owner.IsStatic || owner.DeclaredAccessibility != Accessibility.Public ||
                !owner.GetAttributes().Any(static attribute => attribute.AttributeClass?.ToDisplayString() == "System.Runtime.CompilerServices.CompilerGeneratedAttribute")) return false;
            var declaredFlags = owner.GetMembers("Flags_" + key).OfType<IFieldSymbol>().SingleOrDefault();
            if (declaredFlags == null || !declaredFlags.IsConst || declaredFlags.ConstantValue is not int value || value != flags) return false;
            foreach (var operation in ComponentRegistrationEmitter.Operations(flags)) {
                var methods = owner.GetMembers(operation + "_" + key).OfType<IMethodSymbol>().ToArray();
                if (methods.Length != 1) return false;
                var method = methods[0];
                if (!method.IsStatic || method.Arity != args.Length || method.Parameters.Length != 0 ||
                    method.DeclaredAccessibility != Accessibility.Public ||
                    (operation == "Size" ? method.ReturnType.SpecialType != SpecialType.System_UInt32 : !method.ReturnsVoid) ||
                    !compilation.IsSymbolAccessibleWithin(method, compilation.Assembly)) return false;
            }
        }
        ownerName = "global::" + metadataName;
        return true;
    }
}
