using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ComponentDestroyGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var callbacks = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is StructDeclarationSyntax s && s.BaseList != null,
            static (syntax, cancellation) => Describe(syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol,
                syntax.SemanticModel.Compilation)).Where(static s => s != null).Collect();
        context.RegisterSourceOutput(callbacks.Combine(context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? "")),
            static (output, input) => {
                var bodies = input.Left.Where(static s => s != null).Distinct(StringComparer.Ordinal).OrderBy(static s => s, StringComparer.Ordinal).ToArray();
                if (bodies.Length == 0) return;
                output.AddSource("ME.BECS.ComponentDestroy.g.cs", SourceText.From(
                    "// <auto-generated/>\nnamespace ME.BECS.SourceGenerated {\n[global::Unity.Burst.BurstCompile]\npublic static unsafe class ComponentDestroy_" +
                    ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(input.Right) + " {\n" + string.Join("\n", bodies) + "\n} }", Encoding.UTF8));
            });
    }

    private static string? Describe(INamedTypeSymbol? type, Compilation compilation) {
        if (type == null || !type.IsUnmanagedType || type.IsRefLikeType ||
            compilation.Options is not Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions options || !options.AllowUnsafe ||
            compilation.GetTypeByMetadataName("Unity.Burst.BurstCompileAttribute") == null ||
            compilation.GetTypeByMetadataName("AOT.MonoPInvokeCallbackAttribute") == null ||
            !type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.IComponentDestroy")) return null;
        for (var owner = type; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public || owner.Arity != 0) return null;
        }
        if (!type.GetMembers("Destroy").OfType<IMethodSymbol>().Any(static m => m.DeclaredAccessibility == Accessibility.Public &&
            !m.IsStatic && m.Arity == 0 && m.ReturnsVoid && m.Parameters.Length == 1 && m.Parameters[0].RefKind == RefKind.In &&
            m.Parameters[0].Type.ToDisplayString() == "ME.BECS.Ent")) return null;
        var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var key = ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(name);
        return "public static void Register_" + key + "() => global::ME.BECS.WorldStaticCallbacks.RegisterAutoDestroyCallback<" + name + ">(Destroy_" + key + ");\n" +
            "[global::Unity.Burst.BurstCompile]\n[global::AOT.MonoPInvokeCallback(typeof(global::ME.BECS.AutoDestroyRegistry.DestroyDelegate))]\n" +
            "public static void Destroy_" + key + "(in global::ME.BECS.Ent ent, byte* comp) {\n" +
            "if (comp == null) { default(" + name + ").Destroy(in ent); } else { ((" + name + "*)comp)->Destroy(in ent); }\n}";
    }
}
