using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// Layout is a property of the definition, including definitions nested inside
// generic owners. StructLayout is a CLI pseudo-attribute, absent from imported
// Roslyn attributes. Never infer "tag" merely from that absence.
internal sealed class ComponentLayoutReader {
    internal const string MetadataKey = "ME.BECS.ComponentTag.v1";
    private readonly Compilation compilation;
    private readonly CancellationToken cancellation;
    private readonly Dictionary<IAssemblySymbol, string[]> records = new(SymbolEqualityComparer.Default);
    private readonly Dictionary<IModuleSymbol, Dictionary<string, bool>> modules = new(SymbolEqualityComparer.Default);

    internal ComponentLayoutReader(Compilation compilation, CancellationToken cancellation) {
        this.compilation = compilation;
        this.cancellation = cancellation;
    }

    internal static bool IsSourceTag(INamedTypeSymbol type) {
        if (type.GetMembers().OfType<IFieldSymbol>().Any(static field => !field.IsStatic)) return false;
        return !type.GetAttributes().Where(static attribute =>
                attribute.AttributeClass?.ToDisplayString() == "System.Runtime.InteropServices.StructLayoutAttribute")
            .SelectMany(static attribute => attribute.NamedArguments)
            .Any(static argument => argument.Key == "Size" && argument.Value.Value is int size && size > 1);
    }

    internal static string? Describe(INamedTypeSymbol? type) {
        if (type == null || type.TypeKind != TypeKind.Struct || type.IsRefLikeType ||
            !type.AllInterfaces.Any(static contract => contract.ToDisplayString() == "ME.BECS.IComponentBase")) return null;
        // Metadata strings don't expose private types in emitted C# and need no
        // typeof(open<T>) expressions. Closed discovery/registration stays separate.
        return type.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "\n" + (IsSourceTag(type) ? "1" : "0");
    }

    internal static void Emit(SourceProductionContext output, ImmutableArray<string?> input) {
        var values = input.Where(static value => value != null).Select(static value => value!)
            .Distinct(StringComparer.Ordinal).OrderBy(static value => value, StringComparer.Ordinal).ToArray();
        if (values.Length == 0) return;
        var source = new StringBuilder("// <auto-generated/>\n");
        foreach (var value in values) {
            output.CancellationToken.ThrowIfCancellationRequested();
            source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"").Append(MetadataKey).Append("\", ")
                .Append(SymbolDisplay.FormatLiteral(value, true)).Append(")]\n");
        }
        output.AddSource("ME.BECS.ComponentTags.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    internal bool TryGetTag(INamedTypeSymbol type, out bool tag, out string? error) {
        tag = false;
        error = null;
        var definition = type.OriginalDefinition;
        if (definition.DeclaringSyntaxReferences.Length != 0) {
            tag = IsSourceTag(definition);
            return true;
        }
        if (!this.records.TryGetValue(type.ContainingAssembly, out var records)) {
            records = type.ContainingAssembly.GetAttributes().Where(static attribute =>
                    attribute.AttributeClass?.ToDisplayString() == "System.Reflection.AssemblyMetadataAttribute" &&
                    attribute.ConstructorArguments.Length == 2 && attribute.ConstructorArguments[0].Value as string == MetadataKey)
                .Select(static attribute => attribute.ConstructorArguments[1].Value as string)
                .Where(static value => value != null).Select(static value => value!).ToArray();
            this.records.Add(type.ContainingAssembly, records);
        }
        var prefix = definition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "\n";
        var selected = records.Where(value => value.StartsWith(prefix, StringComparison.Ordinal)).ToArray();
        if (selected.Length != 0) {
            if (selected.Length != 1 || (selected[0] != prefix + "0" && selected[0] != prefix + "1")) {
                error = "Invalid or duplicate source component tag classification: " + definition.ToDisplayString();
                return false;
            }
            tag = selected[0] == prefix + "1";
            return true;
        }
        // Precompiled libraries and old catalogs may have no source classification.
        // Read CLI layout from the compiler-owned reference image (not runtime
        // reflection, IL method analysis or a project/file-system scan).
        try {
            if (!this.modules.TryGetValue(type.ContainingModule, out var tags)) {
                tags = this.ReadModule(type.ContainingModule);
                if (tags == null) {
                    error = "Component layout reference unavailable: " + type.ContainingModule.Name;
                    return false;
                }
                this.modules.Add(type.ContainingModule, tags);
            }
            var names = new Stack<string>();
            for (var owner = definition; owner != null; owner = owner.ContainingType) names.Push(owner.MetadataName);
            var namespaces = new Stack<string>();
            for (var ns = definition.ContainingNamespace; !ns.IsGlobalNamespace; ns = ns.ContainingNamespace) namespaces.Push(ns.Name);
            var name = (namespaces.Count == 0 ? "" : string.Join(".", namespaces) + ".") + string.Join("+", names);
            if (tags.TryGetValue(name, out tag)) return true;
            error = "Component layout definition unavailable: " + name;
        } catch (BadImageFormatException exception) { error = "Invalid component layout metadata: " + exception.Message; }
          catch (IOException exception) { error = "Component layout reference cannot be read: " + exception.Message; }
        return false;
    }

    private Dictionary<string, bool>? ReadModule(IModuleSymbol module) {
        foreach (var reference in this.compilation.References.OfType<PortableExecutableReference>()) {
            this.cancellation.ThrowIfCancellationRequested();
            var symbol = this.compilation.GetAssemblyOrModuleSymbol(reference);
            if (symbol is IAssemblySymbol assembly ? !SymbolEqualityComparer.Default.Equals(assembly, module.ContainingAssembly) :
                !SymbolEqualityComparer.Default.Equals(symbol, module)) continue;
            var metadata = reference.GetMetadata(); // Roslyn-owned copy: no Dispose required.
            var modules = metadata is AssemblyMetadata asm ? asm.GetModules() : metadata is ModuleMetadata single ?
                ImmutableArray.Create(single) : ImmutableArray<ModuleMetadata>.Empty;
            foreach (var item in modules) {
                var reader = item.GetMetadataReader();
                if (reader.GetString(reader.GetModuleDefinition().Name) != module.Name) continue;
                var tags = new Dictionary<string, bool>(StringComparer.Ordinal);
                foreach (var handle in reader.TypeDefinitions) {
                    this.cancellation.ThrowIfCancellationRequested();
                    var type = reader.GetTypeDefinition(handle);
                    var names = new Stack<string>();
                    var owner = handle;
                    string ns;
                    while (true) {
                        var entry = reader.GetTypeDefinition(owner);
                        names.Push(reader.GetString(entry.Name));
                        owner = entry.GetDeclaringType();
                        if (owner.IsNil) { ns = reader.GetString(entry.Namespace); break; }
                        if (names.Count >= 64) throw new BadImageFormatException("Component declaring type nesting exceeds 64 levels.");
                    }
                    var name = (ns.Length == 0 ? "" : ns + ".") + string.Join("+", names);
                    var hasFields = type.GetFields().Any(field =>
                        (reader.GetFieldDefinition(field).Attributes & System.Reflection.FieldAttributes.Static) == 0);
                    tags.Add(name, !hasFields && type.GetLayout().Size <= 1);
                }
                return tags;
            }
        }
        return null;
    }
}
