using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorConfigFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ConfigPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG116", "Invalid config publication input", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG117", "Config publication awaits Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor => System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                var profile = editor ? "Editor" : "Runtime";
                void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                    reason + " in " + file.Path + ". No config fragment was published; regenerate inputs and wait for compilation."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) || document.Owner != compilation.AssemblyName || document.Editor != editor) {
                    Fail("Invalid or duplicate config fragment"); continue;
                }
                var source = new StringBuilder("// <auto-generated/>\n[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    if (compilation.Options is not CSharpCompilationOptions { AllowUnsafe: true } ||
                        compilation.GetTypeByMetadataName("Unity.Burst.BurstCompileAttribute") == null ||
                        compilation.GetTypeByMetadataName("AOT.MonoPInvokeCallbackAttribute") == null ||
                        compilation.GetTypeByMetadataName("UnityEngine.Scripting.PreserveAttribute") == null ||
                        compilation.GetTypeByMetadataName(editor ? "UnityEditor.InitializeOnLoadMethodAttribute" : "UnityEngine.RuntimeInitializeOnLoadMethodAttribute") == null) {
                        Fail("The selected config owner requires unsafe code and Burst/AOT references"); continue;
                    }
                    var resolver = new InputManifestTypes(compilation, output.CancellationToken);
                    var registrations = new StringBuilder();
                    var bodies = new StringBuilder();
                    var valid = true;
                    foreach (var row in document.Entries) {
                        output.CancellationToken.ThrowIfCancellationRequested();
                        Format.TryEntry(row.Value, out var entry);
                        var type = resolver.ResolveDefinition(entry.Component, out var gap);
                        var key = row.Key.ToString(CultureInfo.InvariantCulture);
                        if (entry.Phase == "Masks") {
                            if (!ConfigMaskInputEmitter.TryCreate(type, null, compilation, out var mask)) {
                                Fail("Invalid config mask fields: " + entry.Component + " (" + gap + ")"); valid = false; break;
                            }
                            mask!.AppendEntry(bodies, registrations, key, "ConfigCallbacks_" + profile + ".");
                        } else {
                            var metadata = new StringBuilder();
                            var body = ConfigCollectionsInputEmitter.Describe(type, compilation, null, key, metadata, "ConfigCallbacks_" + profile + ".");
                            if (body == null) { Fail("Invalid config collection contract: " + entry.Component + " (" + gap + ")"); valid = false; break; }
                            if (entry.Phase == "Counts") {
                                var count = ConfigCollectionsInputEmitter.GetCollectionCount(type!).ToString(CultureInfo.InvariantCulture);
                                registrations.Append("public static uint GetCount_").Append(key).Append("() => ").Append(count).Append("u;\n")
                                    .Append("public static void Register_").Append(key).Append("() => global::ME.BECS.StaticTypes<")
                                    .Append(type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">.SetCollectionsCount(").Append(count).Append("u);\n");
                            } else { registrations.Append(metadata); bodies.Append(body); }
                        }
                    }
                    if (!valid) continue;
                    source.Append("namespace ME.BECS.SourceGenerated {\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\n")
                        .Append("[global::Unity.Burst.BurstCompile]\ninternal static unsafe class ConfigCallbacks_").Append(profile).Append(" {\n")
                        .Append(bodies).Append("}\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static unsafe class ConfigFragment_")
                        .Append(profile).Append(" {\nprivate static readonly int[] Ordinals = new int[] { ")
                        .Append(string.Join(",", document.Entries.Select(entry => entry.Key.ToString(CultureInfo.InvariantCulture)))).Append(" };\n")
                        .Append("private static readonly global::System.Action[] Callbacks = new global::System.Action[] {\n")
                        .Append(string.Join(",\n", document.Entries.Select(entry => "Register_" + entry.Key.ToString(CultureInfo.InvariantCulture)))).Append("\n};\n")
                        .Append(registrations)
                        .Append(editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                            "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
                        .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() => global::ME.BECS.BootstrapRuntime.InstallConfigFragment(")
                        .Append(SymbolDisplay.FormatLiteral(document.Plan, true)).Append(", ")
                        .Append(SymbolDisplay.FormatLiteral(document.Owner, true)).Append(", ").Append(document.Count.ToString(CultureInfo.InvariantCulture))
                        .Append(", Ordinals, Callbacks, editor: ").Append(editor ? "true" : "false").Append(");\n} }\n");
                }
                output.AddSource("ME.BECS.ConfigFragment." + profile + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
