using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ConfigCollectionsGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var callbacks = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is StructDeclarationSyntax s && s.BaseList != null,
            static (syntax, cancellation) => Describe(syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol,
                syntax.SemanticModel.Compilation)).Where(static s => s != null).Collect();
        context.RegisterSourceOutput(callbacks.Combine(context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? "")),
            static (output, input) => {
                var bodies = input.Left.Where(static s => s != null).Distinct(StringComparer.Ordinal).OrderBy(static s => s, StringComparer.Ordinal).ToArray();
                if (bodies.Length == 0) return;
                output.AddSource("ME.BECS.ConfigCollections.g.cs", SourceText.From(
                    "// <auto-generated/>\nnamespace ME.BECS.SourceGenerated {\n[global::Unity.Burst.BurstCompile]\npublic static unsafe class ConfigCollections_" +
                    ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(input.Right) + " {\n" + string.Join("\n", bodies) + "\n} }", Encoding.UTF8));
            });
    }

    private static string? Describe(INamedTypeSymbol? type, Compilation compilation) {
        if (type == null || !type.IsUnmanagedType || type.IsRefLikeType ||
            compilation.Options is not CSharpCompilationOptions options || !options.AllowUnsafe ||
            compilation.GetTypeByMetadataName("Unity.Burst.BurstCompileAttribute") == null ||
            compilation.GetTypeByMetadataName("AOT.MonoPInvokeCallbackAttribute") == null ||
            !type.AllInterfaces.Any(static i => i.ToDisplayString() is "ME.BECS.IConfigComponent" or "ME.BECS.IConfigComponentStatic" or "ME.BECS.IConfigComponentShared")) return null;
        for (var owner = type; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public || owner.Arity != 0) return null;
        }
        var fields = type.GetMembers().OfType<IFieldSymbol>().Where(static f => !f.IsStatic && f.DeclaredAccessibility == Accessibility.Public &&
            f.Type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.IUnmanagedList"))
            .OrderBy(static f => f.Type.ToDisplayString(), StringComparer.Ordinal).ToArray();
        if (fields.Length == 0) return null;
        var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var key = ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(name);
        var body = new StringBuilder();
        body.Append("public static uint Count_").Append(key).Append("() => ").Append(fields.Length).Append("u;\n")
            .Append("public static void RegisterCount_").Append(key).Append("() => global::ME.BECS.StaticTypes<").Append(name)
            .Append(">.SetCollectionsCount(").Append(fields.Length).Append("u);\n");
        // Custom implementations need a verified construction contract before emitting their bodies.
        if (fields.Any(static f => f.IsReadOnly || f.IsFixedSizeBuffer || f.IsImplicitlyDeclared ||
            f.Type is not INamedTypeSymbol n || n.OriginalDefinition.ToDisplayString() is not ("ME.BECS.ListAuto<T>" or "ME.BECS.MemArrayAuto<T>"))) return body.ToString();
        body.Append("public static string[] Fields_").Append(key).Append("() => new string[] { ")
            .Append(string.Join(", ", fields.Select(static f => SymbolDisplay.FormatLiteral(f.Name, true)))).Append(" };\n")
            .Append("public static void Register_").Append(key)
            .Append("() => global::ME.BECS.WorldStaticCallbacks.RegisterConfigComponentCallback<").Append(name).Append(">(Apply_").Append(key).Append(");\n")
            .Append("[global::Unity.Burst.BurstCompile]\n[global::AOT.MonoPInvokeCallback(typeof(global::ME.BECS.UnsafeEntityConfig.MethodCallerDelegate))]\n")
            .Append("public static void Apply_").Append(key)
            .Append("(in global::ME.BECS.UnsafeEntityConfig config, void* componentPtr, in global::ME.BECS.Ent ent) {\n")
            .Append("var component = (").Append(name).Append("*)componentPtr;\n");
        foreach (var field in fields) {
            var target = "component->@" + field.Name;
            var fieldType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            body.Append("{\nvar res = config.GetCollectionById(").Append(target).Append(".GetConfigId(), out var data, out var length);\n")
                .Append("if (").Append(target).Append(".IsCreated) ").Append(target).Append(".Dispose();\n")
                .Append("if (res) { ").Append(target).Append(" = new ").Append(fieldType).Append("(in ent, data, length); } else { ")
                .Append(target).Append(" = ");
            if (field.Type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.IMemList"))
                body.Append("new ").Append(fieldType).Append("(in ent, 1u)");
            else body.Append(fieldType).Append(".Empty");
            body.Append("; }\n}\n");
        }
        return body.Append("}\n").ToString();
    }
}
