using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ConfigMaskGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var callbacks = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is StructDeclarationSyntax s && s.BaseList != null,
            static (syntax, cancellation) => Describe(syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol,
                syntax.SemanticModel.Compilation)).Where(static s => s != null).Collect();
        context.RegisterSourceOutput(callbacks.Combine(context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? "")),
            static (output, input) => {
                var bodies = input.Left.Where(static s => s != null).Distinct(StringComparer.Ordinal).OrderBy(static s => s, StringComparer.Ordinal).ToArray();
                if (bodies.Length == 0) return;
                output.AddSource("ME.BECS.ConfigMask.g.cs", SourceText.From(
                    "// <auto-generated/>\nnamespace ME.BECS.SourceGenerated {\n[global::Unity.Burst.BurstCompile]\npublic static unsafe class ConfigMask_" +
                    ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(input.Right) + " {\n" + string.Join("\n", bodies) + "\n} }", Encoding.UTF8));
            });
    }

    private static string? Describe(INamedTypeSymbol? type, Compilation compilation) {
        if (type == null || !type.IsUnmanagedType || type.IsRefLikeType ||
            compilation.Options is not CSharpCompilationOptions options || !options.AllowUnsafe ||
            compilation.GetTypeByMetadataName("Unity.Burst.BurstCompileAttribute") == null ||
            compilation.GetTypeByMetadataName("AOT.MonoPInvokeCallbackAttribute") == null ||
            !type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.IConfigComponent")) return null;
        for (var owner = type; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public || owner.Arity != 0) return null;
        }
        // Preserve symbol order and export it. The transition bridge verifies reflection order
        // before selecting this callback: partial declarations must not silently remap mask bits.
        var fields = type.GetMembers().OfType<IFieldSymbol>().Where(static f => !f.IsStatic && f.DeclaredAccessibility == Accessibility.Public).ToArray();
        if (fields.Length < 2 || fields.Any(static f => f.IsReadOnly || f.IsFixedSizeBuffer || f.IsImplicitlyDeclared)) return null;
        var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var key = ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(name);
        var body = new StringBuilder();
        body.Append("public static string[] Fields_").Append(key).Append("() => new string[] { ")
            .Append(string.Join(", ", fields.Select(static f => SymbolDisplay.FormatLiteral(f.Name, true)))).Append(" };\n");
        body.Append("public static void Register_").Append(key)
            .Append("() => global::ME.BECS.WorldStaticCallbacks.RegisterConfigComponentMaskCallback<").Append(name).Append(">(Apply_").Append(key).Append(");\n")
            .Append("[global::Unity.Burst.BurstCompile]\n[global::AOT.MonoPInvokeCallback(typeof(global::ME.BECS.UnsafeEntityConfig.MethodMaskCallerDelegate))]\n")
            .Append("public static void Apply_").Append(key)
            .Append("(in global::ME.BECS.UnsafeEntityConfig config, void* componentPtr, void* configComponent, void* maskPtr, in global::ME.BECS.Ent ent) {\n")
            .Append("var allocator = ent.World.state.ptr->allocator;\nvar mask = (global::ME.BECS.BitArray*)maskPtr;\nvar component = (").Append(name)
            .Append("*)componentPtr;\nvar source = (").Append(name).Append("*)configComponent;\n");
        for (var i = 0; i < fields.Length; ++i) {
            body.Append("if (mask->IsSet(in allocator, ").Append(i).Append(")) component->@").Append(fields[i].Name)
                .Append(" = source->@").Append(fields[i].Name).Append(";\n");
        }
        return body.Append("}\n").ToString();
    }
}
