using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

internal static class DestroyRegistryAudit {
    internal const string MetadataKey = "ME.BECS.DestroyRegistryAudit.v1";

    internal static void Emit(SourceProductionContext output, Compilation compilation, IReadOnlyList<INamedTypeSymbol> components) {
        var rows = new SortedSet<string>(StringComparer.Ordinal);
        // No source-only inventory may silently freeze a public mutable registry.
        var gaps = new SortedSet<string>(StringComparer.Ordinal) { "RuntimeRegistryNotSealed" };
        var engine = compilation.GetTypeByMetadataName("ME.BECS.Ent")?.ContainingAssembly;
        var pending = new Queue<IAssemblySymbol>(compilation.SourceModule.ReferencedAssemblySymbols);
        var seen = new HashSet<IAssemblySymbol>(SymbolEqualityComparer.Default);
        var accessCount = 0;
        var coverageCount = 0;
        void Access(string assembly, string record) {
            var fields = record.Split('\n');
            if (fields.Length != 8 || fields[0] != "v1" || fields[1] == "<unknown>" ||
                fields[3] is not ("call" or "method-ref" or "storage") || fields[5] is not ("resolved" or "symbolic" or "unresolved" or "engine-storage")) {
                gaps.Add("MalformedRegistryAccess: " + assembly); return;
            }
            ++accessCount;
            rows.Add("A\t" + assembly + "\t" + Convert.ToBase64String(Encoding.UTF8.GetBytes(record)));
            if (fields[5] != "engine-storage") gaps.Add("CustomRegistryAccess: " + assembly + " | " + fields[1] + " | " + fields[5]);
        }
        while (pending.Count > 0) {
            output.CancellationToken.ThrowIfCancellationRequested();
            var assembly = pending.Dequeue();
            if (!seen.Add(assembly)) continue;
            foreach (var module in assembly.Modules)
                foreach (var reference in module.ReferencedAssemblySymbols) pending.Enqueue(reference);
            // An assembly with no typed engine reference cannot use this API directly.
            // Reflection/opaque runtime registration is NOT ruled out by this inventory.
            if (!SymbolEqualityComparer.Default.Equals(assembly, engine) &&
                !assembly.Modules.Any(module => module.ReferencedAssemblySymbols.Contains(engine, SymbolEqualityComparer.Default))) continue;
            var attributes = assembly.GetAttributes().Where(attribute => attribute.AttributeClass?.ToDisplayString() ==
                "System.Reflection.AssemblyMetadataAttribute" && attribute.ConstructorArguments.Length == 2).ToArray();
            var coverage = attributes.Where(attribute => attribute.ConstructorArguments[0].Value as string == DestroyRegistryAccessGenerator.CoverageKey).ToArray();
            if (coverage.Length != 1 || coverage[0].ConstructorArguments[1].Value as string != "v1")
                gaps.Add("MissingRegistryAccessCoverage: " + assembly.Identity);
            else ++coverageCount;
            foreach (var attribute in attributes.Where(attribute => attribute.ConstructorArguments[0].Value as string == DestroyRegistryAccessGenerator.MetadataKey)) {
                if (attribute.ConstructorArguments[1].Value is string record) Access(assembly.Identity.ToString(), record);
                else gaps.Add("MalformedRegistryAccess: " + assembly.Identity);
            }
        }
        // Other generators' outputs are not visible in this compilation. Scan its
        // source directly; the default generated registrations are the manifest list.
        foreach (var tree in compilation.SyntaxTrees) {
            var model = compilation.GetSemanticModel(tree);
            foreach (var node in tree.GetRoot(output.CancellationToken).DescendantNodes().Where(DestroyRegistryAccessGenerator.Candidate)) {
                var record = DestroyRegistryAccessGenerator.Analyze(model, node, output.CancellationToken);
                if (record != null) Access(compilation.Assembly.Identity.ToString(), record);
            }
        }
        for (var index = 0; index < components.Count; ++index)
            rows.Add("D\t" + index.ToString(System.Globalization.CultureInfo.InvariantCulture) + "\t" + MethodSummaryType.From(components[index]).Encode());
        var payload = "v1\nS\tunclosed\nC\t" + coverageCount.ToString(CultureInfo.InvariantCulture) +
            "\nA\t" + accessCount.ToString(CultureInfo.InvariantCulture) + "\nD\t" + components.Count.ToString(CultureInfo.InvariantCulture) + "\n" +
            string.Join("\n", rows) + "\n" + string.Join("\n", gaps.Select(gap => "G\t" + gap));
        var source = new StringBuilder("// <auto-generated/>\n");
        DestroyRegistryAccessGenerator.Attribute(source, MetadataKey, payload);
        output.AddSource("ME.BECS.DestroyRegistryAudit.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
