using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// Effects of one potential registration target, NOT the active runtime registry.
// Keep each lexical site separate: registrations can replace one another and may
// never execute. An analyzed target can itself have incomplete safety/counts/weights.
internal static class DestroyRegistrationEffects {
    internal const string MetadataKey = "ME.BECS.DestroyRegistrationEffects.v1";

    internal static void Emit(SourceProductionContext output, Compilation compilation, IEnumerable<string> accesses,
        IReadOnlyDictionary<(string Assembly, string Id), MethodSummaryGraph.Summary> methods,
        ISet<(string Assembly, string Id)> conflicts) {
        var source = new StringBuilder("// <auto-generated/>\n");
        var count = 0;
        foreach (var access in accesses.Distinct(StringComparer.Ordinal).OrderBy(static value => value, StringComparer.Ordinal)) {
            output.CancellationToken.ThrowIfCancellationRequested();
            var fields = access.Split('\n');
            if (fields.Length == 8 && fields[5] == "engine-storage") continue;
            var rows = new List<string>();
            var reason = Bind(compilation, fields, methods, conflicts, out var operation, out var component, out var arguments, out var method);
            if (reason != null) rows.Add("G\t" + reason);
            else {
                var root = new MethodSummaryGraph.Summary {
                    Id = method!.Id, Environment = method.Environment, RootArguments = arguments,
                    RootAssembly = operation![2], Unresolved = method.Unresolved,
                    Flags = method.Flags.Where(static flag => !flag.StartsWith("job-type=", StringComparison.Ordinal) &&
                        !flag.StartsWith("entity-max-count=", StringComparison.Ordinal) && !flag.StartsWith("weight-base=", StringComparison.Ordinal))
                        .Concat(new[] { "job-type=" + component!.Encode(), "entity-limit-schema=1", "entity-max-count=0", "weight-base=0" }).ToArray(),
                };
                root.Operations.AddRange(method.Operations);
                // The raw pointer is writable storage for the registered component,
                // even if no typed Get/Set call occurs in the callback body.
                root.Operations.Add(new[] { "parameter-override", "0", operation[2], operation[3], operation[4],
                    component!.Encode(), "!mode=2", "!implicit" });
                rows.Add("S\t" + Encode(JobSafetySummary.Analyze(output, compilation, operation[2], root, methods, conflicts, Decode,
                    emitInitializer: false, emitSizeInitializer: false)));
                rows.Add("C\t" + Encode(JobEntitySummary.Analyze(output, compilation, operation[2], root, methods, conflicts, Decode,
                    emitInitializer: false)));
                rows.Add("W\t" + Encode(JobWeightSummary.Analyze(output, compilation, operation[2], root, methods, conflicts, Decode, emitInitializer: false)));
            }
            var payload = "v1\n" + Encode(access) + "\n" + (reason == null ? "analyzed" : "unavailable") + "\n" +
                (reason == null ? "0" : "1") + "\n" + string.Join("\n", rows);
            DestroyRegistryAccessGenerator.Attribute(source, MetadataKey, payload);
            ++count;
        }
        if (count > 0) output.AddSource("ME.BECS.DestroyRegistrationEffects.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string? Bind(Compilation compilation, string[] fields,
        IReadOnlyDictionary<(string Assembly, string Id), MethodSummaryGraph.Summary> methods,
        ISet<(string Assembly, string Id)> conflicts, out string[]? operation, out MethodSummaryType? component,
        out MethodSummaryType[] arguments, out MethodSummaryGraph.Summary? method) {
        operation = null; component = null; arguments = Array.Empty<MethodSummaryType>(); method = null;
        if (fields.Length != 8 || fields[0] != "v1") return "MalformedRegistryAccess";
        if (fields[3] != "call" || fields[5] == "unresolved") return fields[7].Length > 0 ? fields[7] : "UnresolvedRegistration";
        if (fields[5] == "symbolic") return "UnboundRegistrationContext";
        if (fields[5] != "resolved" || !MethodSummaryType.TryDecode(fields[4], out component) || component!.IsOpen || component.IsUnsupported)
            return "UnresolvedRegistrationComponent";
        var symbol = MethodSummaryTypeResolver.Resolve(component, compilation) as INamedTypeSymbol;
        var contract = compilation.GetTypeByMetadataName("ME.BECS.IComponentDestroy");
        if (symbol == null || !symbol.IsUnmanagedType || contract == null || !symbol.AllInterfaces.Contains(contract, SymbolEqualityComparer.Default))
            return "InvalidRegistrationComponent";
        try { operation = Encoding.UTF8.GetString(Convert.FromBase64String(fields[6])).Split('\t'); }
        catch (FormatException) { return "MalformedRegistrationTarget"; }
        if (operation.Length < 5 || operation[0] != "call" || operation[1] != "0" || !operation[3].StartsWith("M:", StringComparison.Ordinal))
            return "MalformedRegistrationTarget";
        var receiver = Decode(operation[4]);
        if (receiver == null || receiver.Kind != 'n' || receiver.IsUnsupported || receiver.IsOpen) return "UnresolvedRegistrationReceiver";
        var bindings = new List<MethodSummaryType>(receiver.Arguments);
        for (var index = 5; index < MethodSummaryContracts.ArgumentEnd(operation); ++index) {
            var argument = Decode(operation[index]);
            if (argument == null || argument.IsOpen || argument.IsUnsupported) return "UnresolvedRegistrationTypeArgument";
            bindings.Add(argument);
        }
        arguments = bindings.ToArray();
        var key = (operation[2], operation[3]);
        if (conflicts.Contains(key)) return "ConflictingRegistrationTarget: " + operation[3];
        if (!methods.TryGetValue(key, out method)) return "MissingRegistrationTarget: " + operation[3];
        return method.Environment.Length == arguments.Length ? null : "RegistrationGenericArityMismatch: " + operation[3];
    }

    private static MethodSummaryType? Decode(string token) => MethodSummaryType.TryDecode(token, out var value) ? value : null;
    private static string Encode(string value) => Convert.ToBase64String(Encoding.UTF8.GetBytes(value));
}
