using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// Potential typed accesses, not proof of execution or a frozen runtime registry.
// This syntax pass also covers static field initializers and escaped method groups,
// which cannot be inferred from just the job/lifecycle reachable method summaries.
[Generator(LanguageNames.CSharp)]
public sealed class DestroyRegistryAccessGenerator : IIncrementalGenerator {
    internal const string MetadataKey = "ME.BECS.DestroyRegistryAccess.v1";
    internal const string CoverageKey = "ME.BECS.DestroyRegistryCoverage.v1";

    internal static bool Candidate(SyntaxNode node) => node is SimpleNameSyntax name &&
        name.Identifier.ValueText is "RegisterAutoDestroyCallback" or "registry";

    internal static IncrementalValueProvider<System.Collections.Immutable.ImmutableArray<string?>> Collect(IncrementalGeneratorInitializationContext context) =>
        context.SyntaxProvider.CreateSyntaxProvider(static (node, _) => SourceAnalysisOptions.Enabled(node.SyntaxTree.Options) && Candidate(node),
            static (syntax, cancellation) => Analyze(syntax.SemanticModel, syntax.Node, cancellation))
            .Where(static row => row != null).Collect();

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var records = Collect(context);
        context.RegisterSourceOutput(records.Combine(context.CompilationProvider), static (output, input) => {
            if (!SourceAnalysisOptions.Enabled(input.Right) || input.Right.GetTypeByMetadataName("ME.BECS.Ent") == null) return;
            var source = new StringBuilder("// <auto-generated/>\n");
            Attribute(source, CoverageKey, "v1");
            foreach (var record in input.Left.Where(row => row != null).Distinct(StringComparer.Ordinal).OrderBy(row => row, StringComparer.Ordinal))
                Attribute(source, MetadataKey, record!);
            output.AddSource("ME.BECS.DestroyRegistryAccess.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }

    internal static void Attribute(StringBuilder source, string key, string value) => source
        .Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
        .Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(key, true)).Append(", ")
        .Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, true)).Append(")]\n");

    internal static string? Analyze(SemanticModel model, SyntaxNode node, CancellationToken cancellation) {
        var engine = model.Compilation.GetTypeByMetadataName("ME.BECS.Ent")?.ContainingAssembly;
        if (engine == null) return null;
        var symbol = model.GetSymbolInfo(node, cancellation).Symbol;
        if (symbol == null || !SymbolEqualityComparer.Default.Equals(symbol.ContainingAssembly, engine)) return null;
        var registration = symbol is IMethodSymbol method && method.OriginalDefinition.GetDocumentationCommentId() ==
            "M:ME.BECS.WorldStaticCallbacks.RegisterAutoDestroyCallback``1(ME.BECS.AutoDestroyRegistry.DestroyDelegate)";
        var storage = symbol is IFieldSymbol field && field.GetDocumentationCommentId() == "F:ME.BECS.StaticTypesDestroyRegistry.registry";
        if (!registration && !storage) return null;
        // nameof is a compile-time reference, not a delegate escape or storage access.
        if (node.Ancestors().OfType<InvocationExpressionSyntax>().Any(invocation =>
            model.GetOperation(invocation, cancellation) is INameOfOperation)) return null;
        var declaration = node.Ancestors().OfType<MemberDeclarationSyntax>().FirstOrDefault();
        var owner = model.GetEnclosingSymbol(node.SpanStart, cancellation);
        var variable = node.Ancestors().OfType<VariableDeclaratorSyntax>().FirstOrDefault();
        if (variable != null && model.GetDeclaredSymbol(variable, cancellation) is IFieldSymbol initializer) owner = initializer;
        var ownerId = owner == null ? null : MethodSummaryIdentity.Get(owner);
        var site = declaration == null ? 0 : declaration.DescendantNodes().Where(Candidate).TakeWhile(candidate => candidate.Span != node.Span).Count();
        var kind = storage ? "storage" : "method-ref";
        var status = "unresolved";
        var reason = storage ? "RegistryStorageAccess" : "EscapedRegistrationAPI";
        var component = registration ? MethodSummaryType.From(((IMethodSymbol)symbol).TypeArguments[0]).Encode() : "";
        var target = "";
        var expression = node.Parent is MemberAccessExpressionSyntax member && member.Name == node ? (SyntaxNode)member : node;
        if (registration && expression.Parent is InvocationExpressionSyntax call && call.Expression == expression &&
            model.GetOperation(call, cancellation) is IInvocationOperation invocation) {
            kind = "call";
            var value = invocation.Arguments.SingleOrDefault(argument => argument.Parameter?.Ordinal == 0)?.Value;
            while (value is IConversionOperation conversion && conversion.OperatorMethod == null) value = conversion.Operand;
            var callback = value is IDelegateCreationOperation { Target: IMethodReferenceOperation reference } ? reference.Method :
                value is IDelegateCreationOperation { Target: IAnonymousFunctionOperation lambda } ? lambda.Symbol : null;
            if (callback != null && callback.IsStatic && !callback.IsAbstract && !callback.IsVirtual) {
                var operation = MethodSummaryContracts.Operation("call", 0, callback, model.Compilation,
                    new Dictionary<INamedTypeSymbol, int?>(SymbolEqualityComparer.Default));
                if (operation != null) {
                    target = Convert.ToBase64String(Encoding.UTF8.GetBytes(operation));
                    status = MethodSummaryType.From(((IMethodSymbol)symbol).TypeArguments[0]).IsOpen ||
                        MethodSummaryType.From(callback.ContainingType).IsOpen || callback.TypeArguments.Any(argument => MethodSummaryType.From(argument).IsOpen)
                        ? "symbolic" : "resolved";
                    reason = "";
                } else reason = "CallbackIdentityUnavailable";
            } else reason = callback == null ? "UnknownRegistrationDelegate" : "InstanceOrVirtualRegistrationDelegate";
        }
        if (storage && owner is IMethodSymbol storageOwner && SymbolEqualityComparer.Default.Equals(storageOwner.ContainingAssembly, engine) &&
            ownerId is "M:ME.BECS.WorldStaticCallbacks.RegisterAutoDestroyCallback``1(ME.BECS.AutoDestroyRegistry.DestroyDelegate)" or
                "M:ME.BECS.AutoDestroyRegistry.Invoke(ME.BECS.safe_ptr{ME.BECS.State},ME.BECS.Ent@,System.UInt32)" or
                "M:ME.BECS.AutoDestroyRegistry.Destroy(ME.BECS.safe_ptr{ME.BECS.State},ME.BECS.Ent@)") {
            status = "engine-storage";
            reason = "";
        }
        return string.Join("\n", "v1", ownerId ?? "<unknown>", site.ToString(CultureInfo.InvariantCulture), kind, component, status, target, reason);
    }
}
