using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorDestroyFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class DestroyPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG114", "Invalid destroy publication input", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG115", "Destroy publication awaits Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor =>
                System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                var profile = editor ? "Editor" : "Runtime";
                void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                    reason + " in " + file.Path + ". No destroy fragment was published; regenerate inputs and wait for compilation."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) ||
                    document.Owner != compilation.AssemblyName || document.Editor != editor) { Fail("Invalid or duplicate destroy fragment"); continue; }
                var source = new StringBuilder("// <auto-generated/>\n");
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    if (compilation.Options is not CSharpCompilationOptions { AllowUnsafe: true } ||
                        compilation.GetTypeByMetadataName("Unity.Burst.BurstCompileAttribute") == null ||
                        compilation.GetTypeByMetadataName("AOT.MonoPInvokeCallbackAttribute") == null ||
                        compilation.GetTypeByMetadataName("UnityEngine.Scripting.PreserveAttribute") == null ||
                        compilation.GetTypeByMetadataName(editor ? "UnityEditor.InitializeOnLoadMethodAttribute" : "UnityEngine.RuntimeInitializeOnLoadMethodAttribute") == null) {
                        Fail("The selected destroy owner requires unsafe code and Burst/AOT references"); continue;
                    }
                    var resolver = new InputManifestTypes(compilation, output.CancellationToken);
                    var callbacks = new List<string>();
                    var registrations = new StringBuilder();
                    var bodies = new StringBuilder();
                    DestroyInputEmitter.AppendInvoker(bodies);
                    var valid = true;
                    foreach (var entry in document.Entries) {
                        output.CancellationToken.ThrowIfCancellationRequested();
                        var type = resolver.ResolveDefinition(entry.Value, out var gap);
                        if (type == null || !type.IsUnmanagedType || type.IsRefLikeType || MethodSummaryType.From(type).IsOpen ||
                            !compilation.IsSymbolAccessibleWithin(type, compilation.Assembly) ||
                            !type.AllInterfaces.Any(contract => contract.ToDisplayString() == "ME.BECS.IComponentDestroy")) {
                            Fail("Cannot publish " + entry.Value + " (" + (gap ?? "requires accessible closed unmanaged IComponentDestroy") + ")");
                            valid = false; break;
                        }
                        var key = entry.Key.ToString(CultureInfo.InvariantCulture);
                        callbacks.Add("Register_" + key);
                        DestroyInputEmitter.AppendRegistration(registrations, type, key, "DestroyCallbacks_" + profile + ".");
                        DestroyInputEmitter.AppendCallback(bodies, type, key);
                    }
                    if (!valid) continue;
                    // Burst roots must not share a type initializer with managed
                    // publication arrays/delegates. Only the body class is Burst-owned.
                    source.Append("namespace ME.BECS.SourceGenerated {\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\n")
                        .Append("[global::Unity.Burst.BurstCompile]\ninternal static unsafe class DestroyCallbacks_").Append(profile).Append(" {\n")
                        .Append(bodies).Append("}\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static unsafe class DestroyFragment_")
                        .Append(profile).Append(" {\nprivate static readonly int[] Ordinals = new int[] { ")
                        .Append(string.Join(",", document.Entries.Select(entry => entry.Key.ToString(CultureInfo.InvariantCulture)))).Append(" };\n")
                        .Append("private static readonly global::System.Action[] Callbacks = new global::System.Action[] {\n")
                        .Append(string.Join(",\n", callbacks)).Append("\n};\n").Append(registrations)
                        .Append(editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                            "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
                        .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() => global::ME.BECS.BootstrapRuntime.InstallDestroyFragment(")
                        .Append(SymbolDisplay.FormatLiteral(document.Plan, true)).Append(", ")
                        .Append(SymbolDisplay.FormatLiteral(document.Owner, true)).Append(", ").Append(document.Count.ToString(CultureInfo.InvariantCulture))
                        .Append(", Ordinals, Callbacks, editor: ").Append(editor ? "true" : "false").Append(");\n} }\n");
                }
                output.AddSource("ME.BECS.DestroyFragment." + profile + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
