using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class GenericSystemGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var methods = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax declaration && declaration.BaseList != null,
            static (syntax, cancellation) => Describe(syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol))
            .Where(static method => method != null).Collect();
        context.RegisterSourceOutput(methods.Combine(context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? string.Empty)),
            static (output, input) => {
                var declarations = input.Left.Where(static m => m != null).Distinct(StringComparer.Ordinal).OrderBy(static m => m, StringComparer.Ordinal).ToArray();
                if (declarations.Length == 0) return;
                var source = "// <auto-generated/>\n#nullable enable\nnamespace ME.BECS.SourceGenerated {\n" +
                    "[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\npublic static class GenericSystems_" +
                    Encode(input.Right) + " {\n" + string.Join("\n", declarations) + "\n} }\n";
                output.AddSource("ME.BECS.GenericSystems.g.cs", SourceText.From(source, Encoding.UTF8));
            });
    }

    private static string? Describe(INamedTypeSymbol? type) {
        if (type == null || type.TypeKind != TypeKind.Struct || type.IsRefLikeType || !type.IsUnmanagedType ||
            !type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.ISystem")) return null;
        var chain = new Stack<INamedTypeSymbol>();
        for (var owner = type; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public) return null;
            chain.Push(owner);
        }
        var parameters = chain.SelectMany(static t => t.TypeParameters).ToArray();
        var names = new Dictionary<ITypeParameterSymbol, string>(SymbolEqualityComparer.Default);
        for (var index = 0; index < parameters.Length; ++index) names.Add(parameters[index], "__T" + index);
        string Name(ITypeSymbol symbol) => string.Concat(symbol.ToDisplayParts(SymbolDisplayFormat.FullyQualifiedFormat).Select(part =>
            part.Symbol is ITypeParameterSymbol parameter && names.TryGetValue(parameter, out var name) ? name : part.ToString()));
        var metadataName = (type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString() + ".") +
            string.Join("+", chain.Select(static t => t.MetadataName));
        var genericSuffix = parameters.Length == 0 ? "" : "<" + string.Join(", ", parameters.Select(parameter => names[parameter])) + ">";
        var constraintsText = new StringBuilder();
        foreach (var parameter in parameters) {
            var constraints = new List<string>();
            if (parameter.HasUnmanagedTypeConstraint) constraints.Add("unmanaged");
            else if (parameter.HasValueTypeConstraint) constraints.Add("struct");
            else if (parameter.HasReferenceTypeConstraint) constraints.Add(parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
            else if (parameter.HasNotNullConstraint) constraints.Add("notnull");
            foreach (var constraint in parameter.ConstraintTypes) {
                if (!IsPublic(constraint)) return null;
                constraints.Add(Name(constraint));
            }
            if (parameter.HasConstructorConstraint && !parameter.HasValueTypeConstraint && !parameter.HasUnmanagedTypeConstraint) constraints.Add("new()");
            if (constraints.Count > 0) constraintsText.Append(" where ").Append(names[parameter]).Append(" : ").Append(string.Join(", ", constraints));
        }
        var typeName = Name(type);
        var source = new StringBuilder("public static void Register_").Append(Encode(metadataName)).Append(genericSuffix)
            .Append("()").Append(constraintsText).Append(" => global::ME.BECS.StaticSystemTypes<")
            .Append(typeName).Append(">.Validate();\n");
        foreach (var phase in new[] { "Awake", "Start", "Update", "Destroy", "DrawGizmos" }) {
            if (!type.AllInterfaces.Any(i => i.ToDisplayString() == "ME.BECS.I" + phase)) continue;
            foreach (var pointerKind in new[] { "Burst", "NoBurst", "Factory" }) {
                source.Append("public static void Aot").Append(pointerKind).Append(phase).Append('_').Append(Encode(metadataName)).Append(genericSuffix)
                    .Append("()").Append(constraintsText).Append(" => global::ME.BECS.SourceGeneratorSystemAot.")
                    .Append(pointerKind).Append(phase).Append('<').Append(typeName).Append(">();\n");
            }
            // Use the same constrained dispatch as the graph/AOT plan. This
            // includes explicit implementations without boxing the system.
            source.Append("public static void Aot").Append(phase).Append('_').Append(Encode(metadataName)).Append(genericSuffix)
                .Append("(ref global::ME.BECS.SystemContext __becsContext)").Append(constraintsText)
                .Append(" { var system = new ").Append(typeName).Append("(); global::ME.BECS.SourceGeneratorSystemCalls.")
                .Append(phase).Append("(ref system, ref __becsContext); }\n");
        }
        return source.ToString();
    }

    // No registration or lifecycle method is invoked while resolving this
    // contract. The caller still owns the selected global order and AOT masks.
    internal static bool TryResolve(INamedTypeSymbol type, Compilation compilation, string operation, out string target) {
        target = "";
        var chain = new Stack<INamedTypeSymbol>();
        for (var owner = type; owner != null; owner = owner.ContainingType) chain.Push(owner);
        var key = Encode((type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString() + ".") +
            string.Join("+", chain.Select(static owner => owner.MetadataName)));
        var arguments = chain.SelectMany(static owner => owner.TypeArguments).ToArray();
        var metadataName = "ME.BECS.SourceGenerated.GenericSystems_" + Encode(type.ContainingAssembly.Name);
        var directLifecycle = new[] { "Awake", "Start", "Update", "Destroy", "DrawGizmos" }
            .Any(phase => operation == "Aot" + phase);
        if (SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, compilation.Assembly)) {
            if (Describe(type.OriginalDefinition) == null) return false;
            if (operation != "Register") {
                var phases = new[] { "Awake", "Start", "Update", "Destroy", "DrawGizmos" };
                if (!phases.Any(phase => (operation == "Aot" + phase || operation == "AotBurst" + phase ||
                        operation == "AotNoBurst" + phase || operation == "AotFactory" + phase) &&
                        type.AllInterfaces.Any(contract => contract.ToDisplayString() == "ME.BECS.I" + phase))) return false;
            }
        } else {
            var owner = type.ContainingAssembly.GetTypeByMetadataName(metadataName);
            if (owner == null || !owner.IsStatic || owner.DeclaredAccessibility != Accessibility.Public ||
                !owner.GetAttributes().Any(static attribute => attribute.AttributeClass?.ToDisplayString() == "System.Runtime.CompilerServices.CompilerGeneratedAttribute")) return false;
            var methods = owner.GetMembers(operation + "_" + key).OfType<IMethodSymbol>().ToArray();
            if (methods.Length != 1) return false;
            var method = methods[0];
            if (!method.IsStatic || !method.ReturnsVoid || method.Arity != arguments.Length ||
                method.DeclaredAccessibility != Accessibility.Public || !compilation.IsSymbolAccessibleWithin(method, compilation.Assembly) ||
                method.Parameters.Length != (directLifecycle ? 1 : 0)) return false;
            if (directLifecycle && (method.Parameters[0].RefKind != RefKind.Ref ||
                method.Parameters[0].Type.ToDisplayString() != "ME.BECS.SystemContext")) return false;
        }
        target = "global::" + metadataName + "." + operation + "_" + key + (arguments.Length == 0 ? "" : "<" +
            string.Join(", ", arguments.Select(static argument => argument.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) + ">");
        return true;
    }

    private static bool IsPublic(ITypeSymbol type) {
        if (type is ITypeParameterSymbol) return true;
        if (type is not INamedTypeSymbol named) return false;
        for (var owner = named; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public) return false;
            if (!owner.TypeArguments.All(IsPublic)) return false;
        }
        return true;
    }

    private static string Encode(string value) {
        return ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(value);
    }
}
