using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class GenericSystemGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var methods = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax declaration && declaration.BaseList != null,
            static (syntax, cancellation) => Describe(syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol))
            .Where(static method => method != null).Collect();
        context.RegisterSourceOutput(methods.Combine(context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? string.Empty)),
            static (output, input) => {
                var declarations = input.Left.Where(static m => m != null).Distinct(StringComparer.Ordinal).OrderBy(static m => m, StringComparer.Ordinal).ToArray();
                if (declarations.Length == 0) return;
                var source = "// <auto-generated/>\nnamespace ME.BECS.SourceGenerated { public static class GenericSystems_" +
                    Encode(input.Right) + " {\n" + string.Join("\n", declarations) + "\n} }\n";
                output.AddSource("ME.BECS.GenericSystems.g.cs", SourceText.From(source, Encoding.UTF8));
            });
    }

    private static string? Describe(INamedTypeSymbol? type) {
        if (type == null || type.TypeKind != TypeKind.Struct || type.IsRefLikeType || !type.IsUnmanagedType ||
            !type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.ISystem")) return null;
        var chain = new Stack<INamedTypeSymbol>();
        for (var owner = type; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public) return null;
            chain.Push(owner);
        }
        var parameters = chain.SelectMany(static t => t.TypeParameters).ToArray();
        if (parameters.Select(static p => p.Name).Distinct(StringComparer.Ordinal).Count() != parameters.Length) return null;
        var metadataName = (type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString() + ".") +
            string.Join("+", chain.Select(static t => t.MetadataName));
        var genericSuffix = parameters.Length == 0 ? "" : "<" + string.Join(", ", parameters.Select(static p => "@" + p.Name)) + ">";
        var constraintsText = new StringBuilder();
        foreach (var parameter in parameters) {
            var constraints = new List<string>();
            if (parameter.HasUnmanagedTypeConstraint) constraints.Add("unmanaged");
            else if (parameter.HasValueTypeConstraint) constraints.Add("struct");
            else if (parameter.HasReferenceTypeConstraint) constraints.Add("class");
            else if (parameter.HasNotNullConstraint) constraints.Add("notnull");
            foreach (var constraint in parameter.ConstraintTypes) {
                if (!IsPublic(constraint)) return null;
                constraints.Add(constraint.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
            if (parameter.HasConstructorConstraint && !parameter.HasValueTypeConstraint && !parameter.HasUnmanagedTypeConstraint) constraints.Add("new()");
            if (constraints.Count > 0) constraintsText.Append(" where @").Append(parameter.Name).Append(" : ").Append(string.Join(", ", constraints));
        }
        var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var source = new StringBuilder("public static void Register_").Append(Encode(metadataName)).Append(genericSuffix)
            .Append("()").Append(constraintsText).Append(" => global::ME.BECS.StaticSystemTypes<")
            .Append(typeName).Append(">.Validate();\n");
        var contextName = "__becsContext";
        while (parameters.Any(p => p.Name == contextName)) contextName += "_";
        foreach (var phase in new[] { "Awake", "Start", "Update", "Destroy", "DrawGizmos" }) {
            if (!type.AllInterfaces.Any(i => i.ToDisplayString() == "ME.BECS.I" + phase)) continue;
            foreach (var pointerKind in new[] { "Burst", "NoBurst", "Factory" }) {
                source.Append("public static void Aot").Append(pointerKind).Append(phase).Append('_').Append(Encode(metadataName)).Append(genericSuffix)
                    .Append("()").Append(constraintsText).Append(" => global::ME.BECS.SourceGeneratorSystemAot.")
                    .Append(pointerKind).Append(phase).Append('<').Append(typeName).Append(">();\n");
            }
            var callable = type.GetMembers("On" + phase).OfType<IMethodSymbol>().Any(static m =>
                !m.IsStatic && m.DeclaredAccessibility == Accessibility.Public && m.Arity == 0 && m.ReturnsVoid &&
                m.Parameters.Length == 1 && m.Parameters[0].RefKind == RefKind.Ref &&
                m.Parameters[0].Type.ToDisplayString() == "ME.BECS.SystemContext");
            if (!callable) continue;
            source.Append("public static void Aot").Append(phase).Append('_').Append(Encode(metadataName)).Append(genericSuffix)
                .Append("(ref global::ME.BECS.SystemContext ").Append(contextName).Append(')').Append(constraintsText)
                .Append(" => new ").Append(typeName).Append("().On").Append(phase).Append("(ref ").Append(contextName).Append(");\n");
        }
        return source.ToString();
    }

    private static bool IsPublic(ITypeSymbol type) {
        if (type is ITypeParameterSymbol) return true;
        if (type is not INamedTypeSymbol named) return false;
        for (var owner = named; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public) return false;
            if (!owner.TypeArguments.All(IsPublic)) return false;
        }
        return true;
    }

    private static string Encode(string value) {
        return ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(value);
    }
}
