using System;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// A stale consumer must not prevent the independent Editor exporter from loading
// its repaired code. This emits NO registrations or valid snapshot on failure.
// Player compilation keeps BECSG100 as an error, regardless of the manifest profile.
internal sealed class InputRecoveryOutput : IDisposable {
    internal const string MetadataKey = "ME.BECS.InputRecovery.v1";
    internal readonly SourceProductionContext Context;
    private readonly Compilation compilation;
    private readonly bool canRecover;
    internal bool Failed { get; private set; }
    internal CancellationToken CancellationToken => this.Context.CancellationToken;

    internal InputRecoveryOutput(SourceProductionContext context, Compilation compilation) {
        this.Context = context;
        this.compilation = compilation;
        this.canRecover = (compilation.AssemblyName == "ME.BECS.Gen.Editor" || compilation.AssemblyName == "ME.BECS.Gen.Runtime") &&
            compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
    }

    internal void ReportDiagnostic(Diagnostic diagnostic) {
        if (diagnostic.Id == "BECSG100" || diagnostic.Id == "BECSG104") {
            this.Failed = true;
            if (this.canRecover) {
                this.Context.ReportDiagnostic(Diagnostic.Create(InputManifestGenerator.Recovery, diagnostic.Location,
                    diagnostic.GetMessage() + " Editor recovery: bootstrap is disabled until the automatic input export succeeds and recompiles. Player builds remain blocked."));
                return;
            }
        }
        this.Context.ReportDiagnostic(diagnostic);
    }

    internal void AddSource(string name, SourceText source) {
        if (!this.Failed) this.Context.AddSource(name, source);
    }

    public void Dispose() {
        if (!this.Failed || !this.canRecover) return;
        var message = this.compilation.AssemblyName +
            " has incomplete BECS inputs. Wait for automatic input recovery and successful compilation before starting worlds/tests.";
        var source = new StringBuilder("// <auto-generated/>\n");
        source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"").Append(MetadataKey).Append("\", \"pending\")]\n");
        // The regular Editor freshness gate cancels Play Mode. This second guard
        // also covers domain-reload-disabled play and callers bypassing that UI.
        source.Append("namespace ME.BECS.SourceGenerated { internal static class IncompleteInputGuard {\n")
            .Append("[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\n")
            .Append("private static void Stop() { throw new global::System.InvalidOperationException(")
            .Append(SymbolDisplay.FormatLiteral(message, true)).Append("); }\n} }\n");
        this.Context.AddSource("ME.BECS.InputRecovery.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
