using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorInputCatalogFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class InputCatalogPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG135", "Invalid input catalog", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG136", "Input catalog awaits Editor recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor => System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            foreach (var group in input.Left.GroupBy(file => System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true))) {
                var editor = group.Key;
                if (editor && !inEditor) continue;
                var file = group.First();
                if (group.Count() != 1 || !Format.TryParse(file.Content!, out var document) || document.Owner != compilation.AssemblyName || document.Editor != editor) {
                    output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                        "Invalid or duplicate input catalog in " + file.Path + ". No compiled input evidence was emitted."));
                    continue;
                }
                var source = new StringBuilder("// <auto-generated/>\n");
                void Metadata(string key, string value) => source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(key, true)).Append(", ").Append(SymbolDisplay.FormatLiteral(value, true)).Append(")]\n");
                Metadata(Format.MetadataKey, Envelope.Metadata(document, file.Content!));
                if (document.Entries.Length != 0) {
                    Format.TryManifest(Envelope.Decode(document.Entries[0].Value), out var manifest);
                    var profile = editor ? "editor" : "runtime";
                    foreach (var row in manifest.Rows) Metadata("ME.BECS.TypeInput.v1", profile + "\t" + row);
                    Metadata("ME.BECS.TypeInputProfile.v1", profile);
                    Metadata("ME.BECS.InputContentHash.v1", ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(manifest.Content));
                    Metadata("ME.BECS.GraphInputSnapshot.v1", manifest.Snapshot);
                    Metadata("ME.BECS.InputTransport.v1", "native-additionalfile");
                    source.Append("namespace ME.BECS.SourceGenerated { [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static class InputCatalog_")
                        .Append(editor ? "Editor" : "Runtime").Append(" { } }\n");
                }
                output.AddSource("ME.BECS.InputCatalog." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
