using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorJobDebugFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class JobDebugPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG126", "Invalid job debug publication", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG127", "Job debug publication awaits Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor =>
                System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                    reason + " in " + file.Path + ". No job debug fragment was published; regenerate inputs and wait for compilation."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) ||
                    document.Owner != compilation.AssemblyName || document.Editor != editor) { Fail("Invalid or duplicate job debug fragment"); continue; }
                var source = new StringBuilder("// <auto-generated/>\n");
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    if (compilation.GetTypeByMetadataName("ME.BECS.BootstrapRuntime") == null ||
                        compilation.GetTypeByMetadataName("UnityEngine.Scripting.PreserveAttribute") == null ||
                        compilation.GetTypeByMetadataName(editor ? "UnityEditor.InitializeOnLoadMethodAttribute" : "UnityEngine.RuntimeInitializeOnLoadMethodAttribute") == null) {
                        Fail("The selected debug owner requires runtime and initialization references"); continue;
                    }
                    var resolver = new InputManifestTypes(compilation, output.CancellationToken);
                    var plans = new List<DebugJobInputPlan>();
                    var valid = true;
                    foreach (var entry in document.Entries) {
                        output.CancellationToken.ThrowIfCancellationRequested();
                        if (DebugJobInputPlan.TryRead(Format.Payload(entry.Value), resolver, compilation, out var plan, out var error)) plans.Add(plan);
                        else { Fail(error + " at global slot " + entry.Key.ToString(CultureInfo.InvariantCulture)); valid = false; break; }
                    }
                    if (!valid) continue;
                    var profile = editor ? "Editor" : "Runtime";
                    // Public wrapper owners must not collide through references
                    // when several participating assemblies are visible together.
                    var debugOwner = "DebugJobs_" + profile + "_" + ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(document.Owner);
                    DebugJobInputEmitter.Append(source, "ME.BECS.SourceGenerated", plans, debugOwner, individual: true);
                    source.Append("namespace ME.BECS.SourceGenerated {\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static class JobDebugFragment_")
                        .Append(profile).Append(" {\nprivate static readonly int[] Ordinals = new int[] { ")
                        .Append(string.Join(",", document.Entries.Select(entry => entry.Key.ToString(CultureInfo.InvariantCulture)))).Append(" };\n")
                        .Append("private static readonly global::System.Action[] Callbacks = new global::System.Action[] { ")
                        .Append(string.Join(",", plans.Select(plan => debugOwner + "." + DebugJobInputEmitter.InitializerName(plan)))).Append(" };\n")
                        .Append(editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                            "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
                        .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() => global::ME.BECS.BootstrapRuntime.InstallJobDebugFragment(")
                        .Append(SymbolDisplay.FormatLiteral(document.Plan, true)).Append(", ").Append(SymbolDisplay.FormatLiteral(document.Owner, true)).Append(", ")
                        .Append(document.Count.ToString(CultureInfo.InvariantCulture)).Append(", Ordinals, Callbacks, editor: ").Append(editor ? "true" : "false").Append(");\n} }\n");
                }
                output.AddSource("ME.BECS.JobDebugFragment." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
