using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class JobEarlyInitGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var declarations = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is StructDeclarationSyntax s && s.BaseList != null,
            static (syntax, cancellation) => Describe(syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol,
                syntax.SemanticModel.Compilation.GetTypeByMetadataName("ME.BECS.Jobs.EarlyInit")))
            .Where(static value => value != null).Collect();
        context.RegisterSourceOutput(declarations.Combine(context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? "")),
            static (output, input) => {
                var bodies = input.Left.Where(static s => s != null).Distinct(StringComparer.Ordinal).OrderBy(static s => s, StringComparer.Ordinal).ToArray();
                if (bodies.Length == 0) return;
                output.AddSource("ME.BECS.JobEarlyInit.g.cs", SourceText.From(
                    "// <auto-generated/>\nnamespace ME.BECS.SourceGenerated { public static class JobEarlyInit_" + Encode(input.Right) +
                    " {\n" + string.Join("\n", bodies) + "\n} }", Encoding.UTF8));
            });
    }

    private static string? Describe(INamedTypeSymbol? job, INamedTypeSymbol? earlyInit) {
        if (job == null || earlyInit == null || !job.IsUnmanagedType || job.IsRefLikeType) return null;
        var owners = new Stack<INamedTypeSymbol>();
        for (var owner = job; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public) return null;
            owners.Push(owner);
        }
        var genericParameters = owners.SelectMany(static t => t.TypeParameters).ToArray();
        if (genericParameters.Length > 1 || (genericParameters.Length > 0 && job.Arity != 0)) return null;
        var genericSuffix = "";
        var constraints = "";
        if (genericParameters.Length == 1) {
            var parameter = genericParameters[0];
            if (!parameter.HasUnmanagedTypeConstraint || !parameter.ConstraintTypes.All(static c => c is INamedTypeSymbol n && IsPublicSimple(n))) return null;
            genericSuffix = "<@" + parameter.Name + ">";
            constraints = " where @" + parameter.Name + " : unmanaged";
            foreach (var constraint in parameter.ConstraintTypes) constraints += ", " + constraint.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }
        var metadataName = (job.ContainingNamespace.IsGlobalNamespace ? "" : job.ContainingNamespace.ToDisplayString() + ".") +
            string.Join("+", owners.Select(static t => t.MetadataName));
        var result = new List<string>();
        var genericBodies = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
        foreach (var contract in job.AllInterfaces.Where(static i => i.ContainingNamespace.ToDisplayString() == "ME.BECS.Jobs")) {
            if (!contract.TypeArguments.All(static a => a is ITypeParameterSymbol p ? p.HasUnmanagedTypeConstraint : a is INamedTypeSymbol n && IsPublicSimple(n) && n.IsUnmanagedType)) continue;
            var arguments = new ITypeSymbol[] { job }.Concat(contract.TypeArguments).ToArray();
            foreach (var method in earlyInit.GetMembers().OfType<IMethodSymbol>()) {
                if (!method.IsStatic || method.DeclaredAccessibility != Accessibility.Public || !method.ReturnsVoid ||
                    method.Parameters.Length != 0 || method.Arity != arguments.Length || !method.Name.StartsWith("Do", StringComparison.Ordinal)) continue;
                var matches = true;
                for (var i = 0; i < method.TypeParameters.Length && matches; ++i) {
                    foreach (var constraint in method.TypeParameters[i].ConstraintTypes) {
                        if (constraint is not INamedTypeSymbol named || named.TypeKind != TypeKind.Interface) { matches = false; break; }
                        var resolvedArguments = named.TypeArguments.Select(a => a is ITypeParameterSymbol p &&
                            SymbolEqualityComparer.Default.Equals(p.ContainingSymbol, method) ? arguments[p.Ordinal] : a).ToArray();
                        var resolved = named.Arity == 0 ? named : named.ConstructedFrom.Construct(resolvedArguments);
                        if (!Implements(arguments[i], resolved)) {
                            matches = false;
                            break;
                        }
                    }
                }
                if (!matches) continue;
                var names = arguments.Select(static a => a.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).ToArray();
                // Exact legacy spelling is the compatibility key. Nonmatching spellings simply fall back.
                var legacy = "EarlyInit." + method.Name + "<" + string.Join(", ", names.Select(static n => n.Replace("global::", ""))) + ">();";
                if (genericParameters.Length == 0) {
                    result.Add("public static void Init_" + HashCall(legacy) + "() => global::ME.BECS.Jobs.EarlyInit." + method.Name +
                        "<" + string.Join(", ", names) + ">();");
                } else {
                    var key = HashCall(metadataName + "|" + method.Name);
                    var body = "public static void InitGeneric_" + key + genericSuffix + "()" + constraints +
                        " => global::ME.BECS.Jobs.EarlyInit." + method.Name + "<" + string.Join(", ", names) + ">();\n" +
                        "public static global::System.Type[] ArgsGeneric_" + key + genericSuffix + "()" + constraints +
                        " => new global::System.Type[] {" + string.Join(", ", names.Select(static n => "typeof(" + n + ")")) + "};";
                    if (!genericBodies.TryGetValue(key, out var bodies)) genericBodies.Add(key, bodies = new HashSet<string>(StringComparer.Ordinal));
                    bodies.Add(body);
                }
            }
        }
        // Ambiguous EarlyInit overloads keep the legacy path rather than silently choosing one.
        foreach (var bodies in genericBodies.Values) if (bodies.Count == 1) result.Add(bodies.Single());
        return result.Count == 0 ? null : string.Join("\n", result.Distinct(StringComparer.Ordinal).OrderBy(static s => s, StringComparer.Ordinal));
    }

    private static bool IsPublicSimple(INamedTypeSymbol type) {
        for (var owner = type; owner != null; owner = owner.ContainingType) {
            if (owner.DeclaredAccessibility != Accessibility.Public || owner.Arity != 0) return false;
        }
        return true;
    }

    private static bool Implements(ITypeSymbol argument, INamedTypeSymbol contract) {
        if (argument is INamedTypeSymbol named) return named.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, contract));
        if (argument is ITypeParameterSymbol parameter) {
            return parameter.ConstraintTypes.Any(c => SymbolEqualityComparer.Default.Equals(c, contract) || Implements(c, contract));
        }
        return false;
    }

    private static string HashCall(string value) {
        return ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(value);
    }

    private static string Encode(string value) {
        return ME.BECS.CodeGeneration.SourceGeneratorNames.Encode(value);
    }
}
