using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorJobSetupFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class JobSetupPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG124", "Invalid job statistics publication", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG125", "Job statistics await Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor =>
                System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                    reason + " in " + file.Path + ". No job statistics fragment was published; regenerate inputs and wait for compilation."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) || document.Owner != compilation.AssemblyName || document.Editor != editor) {
                    Fail("Invalid or duplicate job statistics fragment"); continue;
                }
                var source = new StringBuilder("// <auto-generated/>\n");
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(").Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    if (compilation.GetTypeByMetadataName("Unity.Collections.LowLevel.Unsafe.UnsafeList`1") == null) {
                        Fail("The statistics owner requires a direct Unity.Collections reference; regenerate inputs to select a compatible owner");
                        continue;
                    }
                    if (compilation.GetTypeByMetadataName("ME.BECS.BootstrapRuntime") == null ||
                        compilation.GetTypeByMetadataName("UnityEngine.Scripting.PreserveAttribute") == null ||
                        compilation.GetTypeByMetadataName(editor ? "UnityEditor.InitializeOnLoadMethodAttribute" : "UnityEngine.RuntimeInitializeOnLoadMethodAttribute") == null) {
                        Fail("The statistics owner requires runtime and initialization references"); continue;
                    }
                    if (!Append(source, document, compilation, output.CancellationToken, out var error)) { Fail(error); continue; }
                }
                output.AddSource("ME.BECS.JobSetupFragment." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }

    private static bool Append(StringBuilder source, Envelope.Document document, Compilation compilation, System.Threading.CancellationToken cancellation, out string error) {
        error = "Invalid owner-local job statistics";
        var resolver = new InputManifestTypes(compilation, cancellation);
        var weights = new JobWeightInputEmitter();
        var entities = new JobEntityInputEmitter();
        var debug = new List<DebugJobInputPlan>();
        var groups = new Dictionary<string, uint>(StringComparer.Ordinal);
        var ids = new Dictionary<uint, string>();
        var count = uint.Parse(Format.Unpack(document.Entries[0].Value)[2], CultureInfo.InvariantCulture);
        var ilOrdinal = 0;
        var fallbackOrdinal = 0;
        foreach (var entry in document.Entries) {
            cancellation.ThrowIfCancellationRequested();
            var data = Format.Unpack(entry.Value);
            if (data[2] != count.ToString(CultureInfo.InvariantCulture)) return false;
            foreach (var row in data[6].Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries)) {
                var parts = row.Split('\t');
                if (!uint.TryParse(parts[0], NumberStyles.None, CultureInfo.InvariantCulture, out var id) || id >= count) return false;
                var type = resolver.ResolveDefinition(parts[1], out _);
                var key = parts[2] + "\t" + parts[3];
                if (type == null || key != type.ContainingAssembly.Identity + "\t" + type.GetDocumentationCommentId() ||
                    groups.TryGetValue(key, out var oldId) && oldId != id || ids.TryGetValue(id, out var oldKey) && oldKey != key) return false;
                groups[key] = id; ids[id] = key;
            }
            var weight = data[3].Split('\t');
            if (Envelope.Decode(weight[2]) != data[1]) return false;
            weight[1] = weights.JobCount.ToString(CultureInfo.InvariantCulture);
            if (!weights.Read(weight, resolver, compilation, out error)) return false;
            var entity = data[4].Split('\t');
            if (Envelope.Decode(entity[2]).Split('\n')[1] != data[1]) return false;
            entity[1] = (entity[0] == "job-entity-il" ? ilOrdinal++ : fallbackOrdinal++).ToString(CultureInfo.InvariantCulture);
            if (!(entity[0] == "job-entity-il" ? entities.ReadIL(entity, resolver, compilation, out error) : entities.ReadFallback(entity, resolver, compilation, out error))) return false;
            foreach (var row in data[5].Split('\n')) {
                if (!DebugJobInputPlan.TryRead(Envelope.Decode(row.Split('\t')[2]), resolver, compilation, out var plan, out error) || plan.JobIdentity != data[1]) return false;
                debug.Add(plan);
            }
        }
        var profile = document.Editor ? "Editor" : "Runtime";
        // Friend assemblies can see each other's internal helpers. Keep names
        // owner-specific instead of relying on local-type shadowing (CS0436).
        var suffix = "_" + profile + "_" + ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(document.Owner);
        entities.AppendMetadata(source, "ME.BECS.PublishedJobEntitySelection." + profile + ".v1");
        weights.AppendMetadata(source, "ME.BECS.PublishedJobWeightSelection." + profile + ".v1");
        if (!entities.Append(source, groups, count, suffix, out error)) return false;
        weights.Append(source, suffix);
        JobLayoutInputEmitter.Append(source, compilation, debug, suffix);
        source.Append("namespace ME.BECS.SourceGenerated {\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static class JobSetupFragment_")
            .Append(profile).Append(" {\nprivate static readonly int[] Ordinals = new int[] { ")
            .Append(string.Join(",", document.Entries.Select(entry => entry.Key.ToString(CultureInfo.InvariantCulture)))).Append(" };\n")
            .Append("private static readonly global::System.Action[] Callbacks = new global::System.Action[] { ")
            .Append(string.Join(",", document.Entries.Select(entry => "Initialize_" + entry.Key.ToString(CultureInfo.InvariantCulture)))).Append(" };\n");
        foreach (var entry in document.Entries) {
            var hash = ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(Format.Unpack(entry.Value)[1]);
            source.Append("[global::UnityEngine.Scripting.PreserveAttribute] private static void Initialize_").Append(entry.Key.ToString(CultureInfo.InvariantCulture)).Append("() {\n");
            foreach (var kind in new[] { "JobEntityInputCalls", "JobWeightInputs", "JobLayoutInputs" })
                source.Append(kind).Append(suffix).Append(".Initialize_").Append(hash).Append("();\n");
            source.Append("}\n");
        }
        source.Append(document.Editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
            .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() => global::ME.BECS.BootstrapRuntime.InstallJobSetupFragment(")
            .Append(SymbolDisplay.FormatLiteral(document.Plan, true)).Append(", ").Append(SymbolDisplay.FormatLiteral(document.Owner, true)).Append(", ")
            .Append(document.Count.ToString(CultureInfo.InvariantCulture)).Append(", Ordinals, Callbacks, editor: ").Append(document.Editor ? "true" : "false").Append(");\n} }\n");
        error = ""; return true;
    }
}
