<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../Runtime/Jobs/Generated/Jobs.Components.Tpl.txt" LogicalName="ME.BECS.JobTemplates.Components" />
    <EmbeddedResource Include="../Runtime/Jobs/Generated/Jobs.Aspect.Tpl.txt" LogicalName="ME.BECS.JobTemplates.Aspect" />
    <EmbeddedResource Include="../Runtime/Jobs/Generated/Jobs.ParallelFor.Components.Tpl.txt" LogicalName="ME.BECS.JobTemplates.ParallelFor.Components" />
    <EmbeddedResource Include="../Runtime/Jobs/Generated/Jobs.ParallelFor.Aspect.Tpl.txt" LogicalName="ME.BECS.JobTemplates.ParallelFor.Aspect" />
    <EmbeddedResource Include="../Runtime/Jobs/Generated/Jobs.AspectsComponents_var.Tpl.txt" LogicalName="ME.BECS.JobTemplates.AspectsComponents" />
    <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorNames.cs" Link="SourceGeneratorNames.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorSystemFragmentFormat.cs" Link="SourceGeneratorSystemFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorTypeFragmentFormat.cs" Link="SourceGeneratorTypeFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorEntityFragmentFormat.cs" Link="SourceGeneratorEntityFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorAspectFragmentFormat.cs" Link="SourceGeneratorAspectFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorDestroyFragmentFormat.cs" Link="SourceGeneratorDestroyFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorConfigFragmentFormat.cs" Link="SourceGeneratorConfigFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorNetworkFragmentFormat.cs" Link="SourceGeneratorNetworkFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorViewsFragmentFormat.cs" Link="SourceGeneratorViewsFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorJobInitFragmentFormat.cs" Link="SourceGeneratorJobInitFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorJobSetupFragmentFormat.cs" Link="SourceGeneratorJobSetupFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorJobDebugFragmentFormat.cs" Link="SourceGeneratorJobDebugFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorGraphFragmentFormat.cs" Link="SourceGeneratorGraphFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorBootstrapFragmentFormat.cs" Link="SourceGeneratorBootstrapFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorViewSelectionFragmentFormat.cs" Link="SourceGeneratorViewSelectionFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorSystemDependencyFragmentFormat.cs" Link="SourceGeneratorSystemDependencyFragmentFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorInputCatalogFormat.cs" Link="SourceGeneratorInputCatalogFormat.cs" />
    <Compile Include="../Editor/CodeGenerator/SourceGeneratorThemeMenuFragmentFormat.cs" Link="SourceGeneratorThemeMenuFragmentFormat.cs" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" PrivateAssets="all" />
  </ItemGroup>
  <Target Name="InstallUnityAnalyzer" AfterTargets="Build" Condition="'$(InstallUnityAnalyzer)' == 'true'">
    <MakeDir Directories="$(MSBuildProjectDirectory)/../Runtime/SourceGenerator" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)/../Runtime/SourceGenerator" />
  </Target>
</Project>
