using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

// A runtime publisher may be the only entry point in a bridge/package assembly.
// Root marking must process that assembly even without a scene/type reference.
// One generator owns the attribute, regardless of how many fragment kinds exist.
[Generator(LanguageNames.CSharp)]
public sealed class PublicationRootsGenerator : IIncrementalGenerator {
    private static readonly string[] Kinds = { "System", "Type", "Entity", "Aspect", "Destroy", "Config", "Network", "Views", "JobInit", "JobSetup", "JobDebug", "Graph" };

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => file.Path.EndsWith("Runtime" + Envelope.NativeSuffix, StringComparison.Ordinal))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => (Owner: compilation.AssemblyName ?? "",
                Suffix: ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(compilation.AssemblyName ?? "") + "Runtime" + Envelope.NativeSuffix)))
            .Where(static input => Kinds.Any(kind => System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == kind + "Fragment" + input.Right.Suffix))
            .Select(static (input, cancellation) => (input.Right.Owner, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var attribute = input.Right.GetTypeByMetadataName("UnityEngine.Scripting.AlwaysLinkAssemblyAttribute");
            if (attribute == null || input.Right.Assembly.GetAttributes().Any(item => SymbolEqualityComparer.Default.Equals(item.AttributeClass, attribute))) return;
            foreach (var file in input.Left) {
                if (file.Content == null) continue;
                var index = file.Content.IndexOf('\t');
                if (index < 0) continue;
                var schema = file.Content.Substring(0, index);
                if (!Kinds.Any(kind => schema == "ME.BECS." + kind + "Fragment.v1") ||
                    !Envelope.TryParseEnvelope(file.Content, schema, out var document) || document.Editor ||
                    document.Owner != file.Owner || document.Entries.Length == 0) continue;
                output.AddSource("ME.BECS.PublicationRoots.g.cs", SourceText.From(
                    "// <auto-generated/>\n[assembly: global::UnityEngine.Scripting.AlwaysLinkAssemblyAttribute]\n", Encoding.UTF8));
                break;
            }
        });
    }
}
