using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class RefOpContractGenerator : IIncrementalGenerator {
    internal const string MetadataKey = "ME.BECS.RefOp.v1";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var contracts = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
            static (syntax, cancellation) => {
                var type = syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol;
                if (type == null || !type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.IRefOp")) return null;
                var mode = MethodSummaryContracts.RefModeFromSource(type, syntax.SemanticModel.Compilation);
                var id = type.GetDocumentationCommentId();
                return mode.HasValue && id != null ? id + "\t" + mode.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : null;
            }).Where(static c => c != null).Collect();
        context.RegisterSourceOutput(contracts, static (output, input) => {
            var rows = input.Where(static r => r != null).Distinct(StringComparer.Ordinal).OrderBy(static r => r, StringComparer.Ordinal).ToArray();
            if (rows.Length == 0) return;
            var source = new StringBuilder("// <auto-generated/>\n");
            foreach (var row in rows) {
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"").Append(MetadataKey).Append("\", ")
                    .Append(SymbolDisplay.FormatLiteral(row!, true)).Append(")]\n");
            }
            output.AddSource("ME.BECS.RefOpContracts.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }
}
