using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// Registration reachability roots, not runtime callbacks. A concrete module owns
// its inherited/overridden roots even when the body belongs to another assembly.
internal static class RuntimeUsageRoots {
    private static readonly string[] ModulePhases = { "OnAwake", "OnStart", "OnUpdate", "DoDestroy" };

    internal static void Emit(SourceProductionContext output, Compilation compilation,
        IReadOnlyDictionary<(string Assembly, string Id), MethodSummaryGraph.Summary> methods,
        ISet<(string Assembly, string Id)> conflicts, Func<string, MethodSummaryType?> decode, RuntimeTypeUsage usage) {
        var module = compilation.GetTypeByMetadataName("ME.BECS.Module");
        var initialize = compilation.GetTypeByMetadataName("ME.BECS.IConfigInitialize");
        var destroy = compilation.GetTypeByMetadataName("ME.BECS.IComponentDestroy");
        var source = new StringBuilder("// <auto-generated/>\n");
        var count = 0;
        foreach (var owner in Types(compilation.Assembly.GlobalNamespace).OrderBy(type => type.ToDisplayString(), StringComparer.Ordinal)) {
            output.CancellationToken.ThrowIfCancellationRequested();
            if (owner.IsAbstract || owner.IsRefLikeType || MethodSummaryType.From(owner).IsOpen || !Visible(owner)) continue;
            if (owner.TypeKind == TypeKind.Struct && owner.IsUnmanagedType) {
                foreach (var contract in new[] { initialize, destroy }) {
                    if (contract == null || !owner.AllInterfaces.Contains(contract, SymbolEqualityComparer.Default)) continue;
                    var phase = SymbolEqualityComparer.Default.Equals(contract, initialize) ? "OnInitialize" : "Destroy";
                    var members = contract.GetMembers(phase).OfType<IMethodSymbol>().ToArray();
                    if (members.Length != 1) continue;
                    var target = MethodSummaryInterfaceMap.Implementation(owner, members[0]);
                    Emit(owner, phase, contract, target, members[0]);
                }
            }
            if (owner.TypeKind != TypeKind.Class || module == null || !Derives(owner, module)) continue;
            foreach (var phase in ModulePhases) {
                var slots = module.GetMembers(phase).OfType<IMethodSymbol>().Where(method => !method.IsStatic && (method.IsVirtual || method.IsAbstract)).ToArray();
                if (slots.Length == 1) Emit(owner, phase, null, ViewSafetySummary.MostDerived(owner, slots[0]), null);
            }
        }
        if (count != 0) output.AddSource("ME.BECS.RuntimeCallbackUsage.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));

        void Emit(INamedTypeSymbol owner, string phase, INamedTypeSymbol? contract, IMethodSymbol? target, IMethodSymbol? member) {
            var qualified = JobSafetySummary.ReflectionIdentity(owner);
            if (qualified == null) return;
            var identity = owner.IsGenericType ? qualified : qualified.Substring(0, qualified.Length - owner.ContainingAssembly.Identity.ToString().Length - 2);
            var assembly = target?.ContainingAssembly.Identity.ToString() ?? owner.ContainingAssembly.Identity.ToString();
            var id = target == null ? null : MethodSummaryIdentity.Get(target);
            if (contract != null && member != null && (id == null || !methods.ContainsKey((assembly, id))))
                id = MethodSummaryInterfaceMap.FindSourceBody(MethodSummaryType.From(owner), MethodSummaryType.From(contract),
                    contract.ContainingAssembly.Identity.ToString(), MethodSummaryIdentity.Get(member)!, methods, conflicts);
            id ??= "M:unavailable." + phase;
            methods.TryGetValue((assembly, id), out var body);
            var root = new MethodSummaryGraph.Summary {
                Id = id, Environment = body?.Environment ?? Array.Empty<MethodSummaryType>(),
                RootArguments = MethodSummaryType.From(target?.ContainingType ?? owner).Arguments,
            };
            var binding = target == null || target.IsAbstract || target.Arity != 0 ? null : Bind(output, compilation, owner, identity, phase, contract, target, id);
            var payload = usage.Analyze(output, compilation, assembly, root, methods, conflicts, decode, binding, identity);
            source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"").Append(RuntimeTypeUsage.MetadataKey).Append("\", ")
                .Append(SymbolDisplay.FormatLiteral(payload, true)).Append(")]\n");
            ++count;
        }
    }

    private static string? Bind(SourceProductionContext output, Compilation compilation, INamedTypeSymbol owner, string identity,
        string phase, INamedTypeSymbol? contract, IMethodSymbol target, string id) {
        if (!compilation.IsSymbolAccessibleWithin(owner, compilation.Assembly) ||
            !compilation.IsSymbolAccessibleWithin(target.ContainingType, compilation.Assembly) ||
            target.Parameters.Any(parameter => !compilation.IsSymbolAccessibleWithin(parameter.Type, compilation.Assembly))) return null;
        var name = "RuntimeUsageRoot_" + ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(compilation.Assembly.Identity + "\n" + identity + "\n" + id);
        var source = new StringBuilder("// <auto-generated/>\nnamespace ME.BECS.SourceGenerated { public static class ").Append(name)
            .Append(" { public static global::System.Type GetOwner() => typeof(").Append(owner.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(");\n");
        if (contract != null) {
            // InterfaceMap uses the actual runtime dispatch, including Unity's in/
            // modreq adapter, without ever calling the component implementation.
            source.Append("public static global::System.Reflection.MethodInfo GetRoot() { var map = typeof(")
                .Append(owner.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(").GetInterfaceMap(typeof(")
                .Append(contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append("));\n")
                .Append("for (var index = 0; index < map.InterfaceMethods.Length; ++index) if (map.InterfaceMethods[index].Name == ")
                .Append(SymbolDisplay.FormatLiteral(phase, true)).Append(") return map.TargetMethods[index]; return null; }\n");
        } else {
            source.Append("public static global::System.Reflection.MethodInfo GetRoot() => typeof(")
                .Append(target.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(").GetMethod(")
                .Append(SymbolDisplay.FormatLiteral(target.MetadataName, true))
                .Append(", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly, null, new global::System.Type[] {");
            foreach (var parameter in target.Parameters) {
                source.Append("typeof(").Append(parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(')');
                if (parameter.RefKind != RefKind.None) source.Append(".MakeByRefType()");
                source.Append(',');
            }
            source.Append("}, null);\n");
        }
        source.Append("} }\n");
        output.AddSource("ME.BECS." + name + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return "U\t" + compilation.Assembly.Identity + "\tME.BECS.SourceGenerated." + name + "\tGetRoot\tGetOwner\t" + phase + "\tv1";
    }

    private static bool Derives(INamedTypeSymbol owner, INamedTypeSymbol contract) {
        for (var current = owner.BaseType; current != null; current = current.BaseType)
            if (SymbolEqualityComparer.Default.Equals(current, contract)) return true;
        return false;
    }

    private static bool Visible(INamedTypeSymbol owner) => MethodSummaryType.TypeOwners(owner).All(type => type.DeclaredAccessibility == Accessibility.Public);

    private static IEnumerable<INamedTypeSymbol> Types(INamespaceOrTypeSymbol scope) {
        foreach (var member in scope.GetMembers()) {
            if (member is INamespaceSymbol space) { foreach (var type in Types(space)) yield return type; }
            else if (member is INamedTypeSymbol type) { yield return type; foreach (var nested in Types(type)) yield return nested; }
        }
    }
}
