using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class SystemPrivateInjectionGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var sources = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is StructDeclarationSyntax,
            static (syntax, cancellation) => Describe(
                syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol,
                syntax.SemanticModel.Compilation)).Where(static value => value != null).Collect();
        context.RegisterSourceOutput(sources, static (output, values) => {
            foreach (var source in values.Where(static s => s != null).Distinct(StringComparer.Ordinal).OrderBy(static s => s, StringComparer.Ordinal)) {
                output.CancellationToken.ThrowIfCancellationRequested();
                output.AddSource("ME.BECS.SystemPrivateInjection_" + ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(source!) + ".g.cs",
                    SourceText.From(source!, Encoding.UTF8));
            }
        });
    }

    private static string? Describe(INamedTypeSymbol? system, Compilation compilation) {
        if (system == null || !system.IsUnmanagedType || system.IsRefLikeType ||
            compilation.Options is not CSharpCompilationOptions { AllowUnsafe: true }) return null;
        for (var owner = system; owner != null; owner = owner.ContainingType)
            if (owner.DeclaredAccessibility != Accessibility.Public) return null;
        var contract = compilation.GetTypeByMetadataName("ME.BECS.ISystem");
        var injection = compilation.GetTypeByMetadataName("ME.BECS.InjectSystem`1");
        var isJob = system.AllInterfaces.Any(static i => i.Name.StartsWith("IJob", StringComparison.Ordinal) &&
            (i.ContainingNamespace.ToDisplayString() == "Unity.Jobs" || i.ContainingNamespace.ToDisplayString() == "ME.BECS.Jobs"));
        if (injection == null || (!isJob &&
            !system.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, contract)))) return null;
        var scope = PartialTypeScope.Create(system);
        if (scope == null) return null;
        var source = new StringBuilder("// <auto-generated/>\n").Append(scope.Value.Prefix);
        var count = 0;
        var deltaAttribute = compilation.GetTypeByMetadataName("ME.BECS.InjectDeltaTimeAttribute");
        var softFloat = compilation.GetTypeByMetadataName("sfloat");
        foreach (var field in system.GetMembers().OfType<IFieldSymbol>()) {
            if (field.IsStatic || field.IsReadOnly || field.IsImplicitlyDeclared) continue;
            if (isJob && field.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, deltaAttribute)) &&
                (field.Type.SpecialType == SpecialType.System_UInt32 || field.Type.SpecialType == SpecialType.System_Single ||
                 SymbolEqualityComparer.Default.Equals(field.Type, softFloat))) {
                var deltaHelper = "__BecsInjectDelta_" + ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(field.Name);
                if (system.GetMembers(deltaHelper).Length == 0) {
                    source.Append("[global::System.Runtime.CompilerServices.CompilerGenerated]\npublic static unsafe void ").Append(deltaHelper)
                        .Append("(ref ").Append(system.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(" job, ushort worldId) {\n")
                        .Append("var dtMs = global::ME.BECS.Worlds.GetWorldDeltaTime(worldId);\n")
                        .Append("var context = global::ME.BECS.SystemContext.Create(dtMs, default, default);\njob.@")
                        .Append(field.Name).Append(" = context.")
                        .Append(field.Type.SpecialType == SpecialType.System_UInt32 ? "deltaTimeMs" : "deltaTime").Append("; }\n");
                    ++count;
                }
            }
            if ((!isJob && field.DeclaredAccessibility == Accessibility.Public) ||
                field.Type is not INamedTypeSymbol data || !SymbolEqualityComparer.Default.Equals(data.OriginalDefinition, injection)) continue;
            var helper = "__BecsInject_" + ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(field.Name);
            if (system.GetMembers(helper).Length != 0) continue;
            var target = data.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            source.Append("[global::System.Runtime.CompilerServices.CompilerGenerated]\npublic static unsafe void ").Append(helper).Append("(ref ")
                .Append(system.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(" system, void* target) { system.@")
                .Append(field.Name).Append(" = global::ME.BECS.InjectSystem<").Append(target)
                .Append(">.FromPointer(target); }\n");
            ++count;
        }
        return count == 0 ? null : source.Append(scope.Value.Suffix).ToString();
    }
}
