using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorSystemDependencyFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class SystemDependencyPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Unavailable = new DiagnosticDescriptor("BECSG134", "System dependency hints are unavailable", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, true))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right.WithOptions(input.Right.Options.WithMetadataImportOptions(MetadataImportOptions.All));
            if (!compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"))) return;
            void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(Unavailable, Location.None,
                reason + ". Graph diagnostic hints were not emitted; this does not change runtime scheduling."));
            if (input.Left.Length > 1) { Fail("Multiple Editor dependency diagnostic inputs"); return; }
            foreach (var file in input.Left) {
                if (!Format.TryParse(file.Content!, out var document) || document.Owner != compilation.AssemblyName) { Fail("Invalid dependency diagnostic input: " + file.Path); continue; }
                var source = new StringBuilder("// <auto-generated/>\n[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    var plans = new SystemDependencyInputEmitter();
                    var resolver = new InputManifestTypes(compilation, output.CancellationToken);
                    var valid = true;
                    foreach (var row in Format.Rows(document.Entries[0].Value)) {
                        output.CancellationToken.ThrowIfCancellationRequested();
                        if (!plans.Read(row.Split('\t'), resolver, compilation, out var error)) { Fail(error); valid = false; break; }
                        source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"ME.BECS.SystemDependencyInputs.v1\", ")
                            .Append(SymbolDisplay.FormatLiteral(row, true)).Append(")]\n");
                    }
                    if (!valid) continue;
                    if (!plans.Validate(resolver, compilation, out var planError)) { Fail(planError); continue; }
                    plans.AppendMetadata(source);
                    plans.Append(source);
                }
                output.AddSource("ME.BECS.SystemDependencyFragment.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
