using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class SystemPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG106", "Invalid system publication input", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG107", "System publication awaits Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor =>
                System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                    reason + " in " + file.Path + ". No system fragment was published; regenerate inputs and wait for compilation."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) ||
                    document.Owner != compilation.AssemblyName || document.Editor != editor) { Fail("Invalid or duplicate system fragment"); continue; }
                var source = new StringBuilder("// <auto-generated/>\n");
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Format.Metadata(document, file.Content!), true)).Append(")]\n");
                // Empty owner selection is a tombstone, not an initializer/root.
                if (document.Entries.Length == 0) {
                    output.AddSource("ME.BECS.SystemFragment." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
                    continue;
                }
                var resolver = new InputManifestTypes(compilation, output.CancellationToken);
                var callbacks = new List<string>();
                var bodies = new StringBuilder();
                var valid = true;
                foreach (var entry in document.Entries) {
                    var type = resolver.ResolveDefinition(entry.Value, out var gap);
                    if (type == null || !type.IsUnmanagedType || MethodSummaryType.From(type).IsOpen ||
                        !compilation.IsSymbolAccessibleWithin(type, compilation.Assembly) ||
                        !type.AllInterfaces.Any(contract => contract.ToDisplayString() == "ME.BECS.ISystem")) {
                        Fail("Cannot publish " + entry.Value + " (" + (gap ?? "requires accessible closed unmanaged ISystem") + ")");
                        valid = false; break;
                    }
                    if (GenericSystemGenerator.TryResolve(type, compilation, "Register", out var target)) callbacks.Add(target);
                    else {
                        var method = "Register_" + entry.Key.ToString(CultureInfo.InvariantCulture);
                        bodies.Append("private static void ").Append(method).Append("() => global::ME.BECS.StaticSystemTypes<")
                            .Append(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">.Validate();\n");
                        callbacks.Add(method);
                    }
                }
                if (!valid) continue;
                source.Append("namespace ME.BECS.SourceGenerated {\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static class SystemFragment_")
                    .Append(editor ? "Editor" : "Runtime").Append(" {\nprivate static readonly int[] Ordinals = new int[] { ")
                    .Append(string.Join(",", document.Entries.Select(entry => entry.Key.ToString(CultureInfo.InvariantCulture)))).Append(" };\n")
                    .Append("private static readonly global::System.Action[] Callbacks = new global::System.Action[] {\n")
                    .Append(string.Join(",\n", callbacks)).Append("\n};\n").Append(bodies)
                    .Append(editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                        "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
                    .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() => global::ME.BECS.BootstrapRuntime.InstallSystemFragment(")
                    .Append(SymbolDisplay.FormatLiteral(document.Plan, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(document.Owner, true)).Append(", ").Append(document.Count.ToString(CultureInfo.InvariantCulture))
                    .Append(", Ordinals, Callbacks, editor: ").Append(editor ? "true" : "false").Append(");\n} }\n");
                output.AddSource("ME.BECS.SystemFragment." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
