using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

internal static class SystemDirectRootCatalog {
    internal static string? Emit(SourceProductionContext output, Compilation compilation, string rootAssembly,
        MethodSummaryGraph.Summary root, ISet<string> emitted) {
        var roots = DocumentationCommentId.GetSymbolsForDeclarationId(root.Id, compilation).OfType<IMethodSymbol>()
            .Where(method => method.ContainingAssembly.Identity.ToString() == rootAssembly).ToArray();
        var arguments = root.RootArguments ?? root.Environment;
        if (roots.Length != 1 || roots[0].Arity != 0 || roots[0].IsStatic || root.Environment.Length != arguments.Length || arguments.Any(type => type.IsOpen)) return null;
        var environment = new Dictionary<string, MethodSummaryType>(StringComparer.Ordinal);
        for (var index = 0; index < arguments.Length; ++index) environment[root.Environment[index].Identity] = arguments[index];
        var owner = MethodSummaryTypeResolver.Resolve(MethodSummaryType.From(roots[0].ContainingType).Substitute(environment), compilation) as INamedTypeSymbol;
        if (owner == null || !compilation.IsSymbolAccessibleWithin(owner, compilation.Assembly)) return null;
        var methods = owner.GetMembers().OfType<IMethodSymbol>()
            .Where(method => SymbolEqualityComparer.Default.Equals(method.OriginalDefinition, roots[0].OriginalDefinition)).ToArray();
        if (methods.Length != 1 || methods[0].Parameters.Any(parameter => !compilation.IsSymbolAccessibleWithin(parameter.Type, compilation.Assembly))) return null;
        var method = methods[0];
        var identity = root.Flags.First(flag => flag.StartsWith("system-type=", StringComparison.Ordinal)).Substring("system-type=".Length);
        var name = "SystemDirectRoot_" + ME.BECS.CodeGeneration.SourceGeneratorNames.Hash(compilation.Assembly.Identity + "\n" + identity + "\n" + root.Id);
        if (emitted.Add(name)) {
            var source = new StringBuilder("// <auto-generated/>\nnamespace ME.BECS.SourceGenerated { public static class ").Append(name)
                .Append(" { public static global::System.Reflection.MethodInfo GetRoot() => typeof(")
                .Append(owner.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(").GetMethod(")
                .Append(SymbolDisplay.FormatLiteral(method.MetadataName, true))
                .Append(", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly, null, new global::System.Type[] {");
            foreach (var parameter in method.Parameters) {
                source.Append("typeof(").Append(parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(')');
                if (parameter.RefKind != RefKind.None) source.Append(".MakeByRefType()");
                source.Append(',');
            }
            source.Append("}, null); } }\n");
            output.AddSource("ME.BECS." + name + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        }
        return "R\t" + compilation.Assembly.Identity + "\tME.BECS.SourceGenerated." + name + "\tGetRoot\tv1";
    }
}
