using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// Definition-level properties also hold for every closed specialization of a generic struct.
[Generator(LanguageNames.CSharp)]
public sealed class SystemLifecycleGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax declaration && declaration.BaseList != null,
            static (syntax, cancellation) => Describe(syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol))
            .Where(static row => row != null);
        context.RegisterSourceOutput(candidates.Collect(), static (production, rows) => Emit(production, rows));
    }

    private static string? Describe(INamedTypeSymbol? type) {
        if (type == null || type.TypeKind != TypeKind.Struct || type.IsRefLikeType ||
            !type.AllInterfaces.Any(static i => i.ToDisplayString() == "ME.BECS.ISystem")) return null;
        var ownerNames = new Stack<string>();
        for (var owner = type; owner != null; owner = owner.ContainingType) ownerNames.Push(owner.MetadataName);
        var name = (type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString() + ".") + string.Join("+", ownerNames);
        var present = 0;
        var burst = 0;
        var discarded = 0;
        var phases = new[] { "Awake", "Start", "Update", "Destroy", "DrawGizmos" };
        for (var index = 0; index < phases.Length; ++index) {
            var contract = type.AllInterfaces.FirstOrDefault(i => i.ToDisplayString() == "ME.BECS.I" + phases[index]);
            if (contract == null) continue;
            var member = contract.GetMembers("On" + phases[index]).OfType<IMethodSymbol>().SingleOrDefault();
            if (member == null || type.FindImplementationForInterfaceMember(member) is not IMethodSymbol method) return null;
            present |= 1 << index;
            if (HasAttribute(method, "Unity.Burst.BurstCompileAttribute")) burst |= 1 << index;
            if (HasAttribute(method, "ME.BECS.WithoutBurstAttribute")) discarded |= 1 << index;
        }
        return name + "\t" + present.ToString(CultureInfo.InvariantCulture) + "\t" + burst.ToString(CultureInfo.InvariantCulture) +
            "\t" + discarded.ToString(CultureInfo.InvariantCulture);
    }

    private static bool HasAttribute(ISymbol symbol, string name) {
        foreach (var attribute in symbol.GetAttributes())
            for (var type = attribute.AttributeClass; type != null; type = type.BaseType)
                if (type.ToDisplayString() == name) return true;
        return false;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<string?> rows) {
        var output = new StringBuilder("// <auto-generated/>\n");
        foreach (var row in rows.Where(static row => row != null).Distinct().OrderBy(static row => row, StringComparer.Ordinal))
            output.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"ME.BECS.SystemLifecycle.v1\", ")
                .Append(SymbolDisplay.FormatLiteral(row!, true)).Append(")]\n");
        context.AddSource("ME.BECS.SystemLifecycle.g.cs", SourceText.From(output.ToString(), Encoding.UTF8));
    }
}
