using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorThemeMenuFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ThemeMenuPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Unavailable = new DiagnosticDescriptor("BECSG137", "Theme menus are unavailable", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, true))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            if (!compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"))) return;
            void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(Unavailable, Location.None,
                reason + ". Theme menus were not emitted; this does not affect world initialization."));
            if (input.Left.Length > 1) { Fail("Multiple theme menu input files"); return; }
            foreach (var file in input.Left) {
                if (!Format.TryParse(file.Content!, out var document) || document.Owner != compilation.AssemblyName) { Fail("Invalid theme input: " + file.Path); continue; }
                var source = new StringBuilder("// <auto-generated/>\n[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    var owner = compilation.GetTypeByMetadataName("ME.BECS.Editor.Themes");
                    if (owner == null || !SymbolEqualityComparer.Default.Equals(owner.ContainingAssembly, compilation.Assembly)) { Fail("Theme menus must be emitted beside Themes"); continue; }
                    var menus = new ThemeMenuInputEmitter();
                    var valid = true;
                    foreach (var row in Format.Rows(document.Entries[0].Value)) {
                        output.CancellationToken.ThrowIfCancellationRequested();
                        if (!menus.Read(row.Split('\t'), editor: true, out var error)) { Fail(error); valid = false; break; }
                    }
                    if (!valid) continue;
                    if (!menus.Validate(compilation, out var planError)) { Fail(planError); continue; }
                    menus.AppendMetadata(source);
                    menus.Append(source);
                }
                output.AddSource("ME.BECS.ThemeMenus.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
