using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorTypeFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class TypePublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG108", "Invalid component publication input", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG109", "Component publication awaits Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor =>
                System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            // Classification must see explicit interface implementations/private
            // fields in imported components just as the aggregate classifier does.
            if (compilation.Options.MetadataImportOptions != MetadataImportOptions.All)
                compilation = compilation.WithOptions(compilation.Options.WithMetadataImportOptions(MetadataImportOptions.All));
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                    reason + " in " + file.Path + ". No component/group fragment was published; regenerate inputs and wait for compilation."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) ||
                    document.Owner != compilation.AssemblyName || document.Editor != editor) { Fail("Invalid or duplicate component/group fragment"); continue; }
                var source = new StringBuilder("// <auto-generated/>\n");
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length == 0) {
                    output.AddSource("ME.BECS.TypeFragment." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
                    continue;
                }
                var resolver = new InputManifestTypes(compilation, output.CancellationToken);
                var layouts = new ComponentLayoutReader(compilation, output.CancellationToken);
                var targets = new Dictionary<INamedTypeSymbol, (int Flags, string Owner, string Key, string Arguments)>(SymbolEqualityComparer.Default);
                var callbacks = new List<string>();
                var bodies = new StringBuilder();
                var aot = new StringBuilder();
                var valid = true;
                foreach (var item in document.Entries) {
                    output.CancellationToken.ThrowIfCancellationRequested();
                    Format.TryEntry(item.Value, out var entry);
                    var type = resolver.ResolveDefinition(entry.Component, out var gap);
                    if (type == null || !type.IsUnmanagedType || MethodSummaryType.From(type).IsOpen ||
                        !compilation.IsSymbolAccessibleWithin(type, compilation.Assembly) ||
                        !type.AllInterfaces.Any(contract => contract.ToDisplayString() == "ME.BECS.IComponentBase")) {
                        Fail("Cannot publish " + entry.Component + " (" + (gap ?? "requires accessible closed unmanaged IComponentBase") + ")");
                        valid = false; break;
                    }
                    if (entry.Phase == "Group") {
                        var group = resolver.ResolveDefinition(entry.Group, out var groupGap);
                        if (group == null || !compilation.IsSymbolAccessibleWithin(group, compilation.Assembly) || !MatchesGroup(type, group)) {
                            Fail("Invalid or stale group for " + entry.Component + " (" + groupGap + ")"); valid = false; break;
                        }
                        if (MethodSummaryType.From(group).IsOpen) group = group.ConstructUnboundGenericType();
                        var method = "Group_" + item.Key.ToString(CultureInfo.InvariantCulture);
                        bodies.Append("private static void ").Append(method).Append("() => global::ME.BECS.StaticTypes<")
                            .Append(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">.ApplyGroup(typeof(")
                            .Append(group.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append("));\n");
                        callbacks.Add(method);
                        continue;
                    }
                    if (!targets.TryGetValue(type, out var target)) {
                        if (!layouts.TryGetTag(type, out var tag, out var layoutGap)) { Fail("Cannot classify " + entry.Component + ": " + layoutGap); valid = false; break; }
                        var flags = ComponentRegistrationFlags.Get(type, tag);
                        if ((flags & 1) == 0 && ComponentRegistrationFlags.HasInvalidDefault(type)) {
                            Fail("Invalid component Default: " + entry.Component); valid = false; break;
                        }
                        if (ComponentRegistrationGenerator.TryResolve(type, flags, compilation, out var owner, out var key, out var arguments))
                            target = (flags, owner!, key, arguments);
                        else {
                            key = "Local_" + item.Key.ToString(CultureInfo.InvariantCulture);
                            ComponentRegistrationEmitter.Append(bodies, type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), flags, key);
                            target = (flags, "", key, "");
                        }
                        targets.Add(type, target);
                    }
                    if (!ComponentRegistrationEmitter.Operations(target.Flags).Contains(entry.Phase)) {
                        Fail("Stale component registration phase: " + entry.Phase + " / " + entry.Component); valid = false; break;
                    }
                    var prefix = target.Owner.Length == 0 ? "" : target.Owner + ".";
                    var suffix = "_" + target.Key + target.Arguments;
                    callbacks.Add(prefix + entry.Phase + suffix);
                    var ordinal = item.Key.ToString(CultureInfo.InvariantCulture);
                    bodies.Append("public static void Aot_").Append(ordinal).Append("() => ").Append(prefix)
                        .Append("Aot").Append(entry.Phase.Substring("Register".Length)).Append(suffix).Append("();\n");
                    aot.Append("Aot_").Append(ordinal).Append("();\n");
                    if (entry.Phase == "Register") {
                        // The exact selected owner exports the flags it used, not
                        // a second aggregate classification of the same component.
                        bodies.Append("public const int Flags_").Append(ordinal).Append(" = ").Append(target.Flags.ToString(CultureInfo.InvariantCulture)).Append(";\n")
                            .Append("public static uint Size_").Append(ordinal).Append("() => ")
                            .Append(prefix).Append("Size").Append(suffix).Append("();\n");
                    }
                }
                if (!valid) continue;
                source.Append("namespace ME.BECS.SourceGenerated {\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static class TypeFragment_")
                    .Append(editor ? "Editor" : "Runtime").Append(" {\nprivate static readonly int[] Ordinals = new int[] { ")
                    .Append(string.Join(",", document.Entries.Select(entry => entry.Key.ToString(CultureInfo.InvariantCulture)))).Append(" };\n")
                    .Append("private static readonly global::System.Action[] Callbacks = new global::System.Action[] {\n")
                    .Append(string.Join(",\n", callbacks)).Append("\n};\n").Append(bodies)
                    .Append("[global::UnityEngine.Scripting.PreserveAttribute]\npublic static void PreserveReferences() {\n").Append(aot).Append("}\n")
                    .Append(editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                        "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
                    .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() => global::ME.BECS.BootstrapRuntime.InstallTypeFragment(")
                    .Append(SymbolDisplay.FormatLiteral(document.Plan, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(document.Owner, true)).Append(", ").Append(document.Count.ToString(CultureInfo.InvariantCulture))
                    .Append(", Ordinals, Callbacks, editor: ").Append(editor ? "true" : "false").Append(");\n} }\n");
                output.AddSource("ME.BECS.TypeFragment." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }

    private static bool MatchesGroup(INamedTypeSymbol component, INamedTypeSymbol group) {
        var attributes = component.GetAttributes().Where(attribute => attribute.AttributeClass?.ToDisplayString() == "ME.BECS.ComponentGroupAttribute").ToArray();
        if (attributes.Length != 1 || attributes[0].ConstructorArguments.Length != 1) return false;
        var declared = attributes[0].ConstructorArguments[0].Value as INamedTypeSymbol;
        foreach (var argument in attributes[0].NamedArguments) if (argument.Key == "groupType") declared = argument.Value.Value as INamedTypeSymbol;
        if (declared != null && MethodSummaryType.From(declared).IsOpen) declared = declared.ConstructUnboundGenericType();
        if (MethodSummaryType.From(group).IsOpen) group = group.ConstructUnboundGenericType();
        return SymbolEqualityComparer.Default.Equals(declared, group);
    }
}
