using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

internal static class ViewSafetySummary {
    // v2 binds actual virtual/interface callback slots, not same-named user methods.
    internal const string MetadataKey = "ME.BECS.ViewSafety.v2";
    internal const string DispatchMetadataKey = "ME.BECS.ViewCallbackDispatch.v1";

    internal static void Emit(SourceProductionContext output, Compilation compilation,
        IReadOnlyDictionary<(string Assembly, string Id), MethodSummaryGraph.Summary> methods,
        ISet<(string Assembly, string Id)> conflicts) {
        var view = compilation.GetTypeByMetadataName("ME.BECS.Views.EntityView");
        var module = compilation.GetTypeByMetadataName("ME.BECS.Views.IViewModule");
        if (view == null && module == null) return;
        IEnumerable<INamedTypeSymbol> Types(INamespaceOrTypeSymbol owner) {
            foreach (var member in owner.GetMembers()) {
                if (member is INamespaceSymbol space) {
                    foreach (var item in Types(space)) yield return item;
                } else if (member is INamedTypeSymbol type) {
                    yield return type;
                    foreach (var item in Types(type)) yield return item;
                }
            }
        }
        var source = new StringBuilder("// <auto-generated/>\n");
        var count = 0;
        var decoded = new Dictionary<string, MethodSummaryType?>(StringComparer.Ordinal);
        MethodSummaryType? Decode(string token) {
            if (!decoded.TryGetValue(token, out var value)) {
                if (!MethodSummaryType.TryDecode(token, out value)) value = null;
                decoded.Add(token, value);
            }
            return value;
        }
        foreach (var type in Types(compilation.Assembly.GlobalNamespace).OrderBy(static t => t.ToDisplayString(), StringComparer.Ordinal)) {
            if (type.IsAbstract || MethodSummaryType.From(type).IsOpen ||
                (!IsView(type, view) && !type.AllInterfaces.Contains(module, SymbolEqualityComparer.Default))) continue;
            var name = string.Join("+", MethodSummaryType.TypeOwners(type).Select(static owner => owner.MetadataName));
            if (!type.ContainingNamespace.IsGlobalNamespace) name = type.ContainingNamespace.ToDisplayString() + "." + name;
            // A view may also be used as an IViewModule. These roles can dispatch to
            // different bodies, so their catalogs must not alias by owner and phase alone.
            var phases = IsView(type, view) && type.AllInterfaces.Contains(module, SymbolEqualityComparer.Default)
                ? new[] { "ApplyState", "ApplyStateParallel", "module:ApplyState", "module:ApplyStateParallel" }
                : new[] { "ApplyState", "ApplyStateParallel" };
            foreach (var phase in phases) {
                output.CancellationToken.ThrowIfCancellationRequested();
                var candidates = Callbacks(type, phase, view, compilation);
                if (candidates.Length == 0) continue; // No callback, same as the discovery feeder.
                string payload;
                var method = candidates[0];
                var id = MethodSummaryIdentity.Get(method);
                var assembly = method.ContainingAssembly.Identity.ToString();
                if (candidates.Length == 1 && method.Arity == 0 && !method.IsAbstract && id != null && !MethodSummaryType.From(method.ContainingType).IsOpen) {
                    // Preserve the source virtual/interface dispatch before Unity
                    // introduces metadata-only in/modreq forwarding methods.
                    var dispatch = string.Join("\n", "v1", name, phase, MethodSummaryType.From(method.ContainingType).Encode(), assembly, id);
                    source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"").Append(DispatchMetadataKey).Append("\", ")
                        .Append(SymbolDisplay.FormatLiteral(dispatch, true)).Append(")]\n");
                }
                if (candidates.Length != 1 || method.Arity != 0 || method.IsAbstract || id == null ||
                    !methods.TryGetValue((assembly, id), out var summary)) {
                    payload = name + "\n" + (id ?? "M:unavailable") + "\n1\nG\tViewCallbackUnavailableOrAmbiguous";
                } else {
                    var root = new MethodSummaryGraph.Summary {
                        Id = summary.Id, Environment = summary.Environment, Unresolved = summary.Unresolved,
                        Flags = summary.Flags.Where(static flag => !flag.StartsWith("job-type=", StringComparison.Ordinal)).Concat(new[] { "job-type=" + name }).ToArray(),
                        RootArguments = MethodSummaryType.From(method.ContainingType).Arguments,
                    };
                    root.Operations.AddRange(summary.Operations);
                    if (root.RootArguments.Length != root.Environment.Length) {
                        payload = name + "\n" + id + "\n1\nG\tViewCallbackGenericContextUnavailable";
                    } else payload = JobSafetySummary.Analyze(output, compilation, assembly, root, methods, conflicts, Decode, emitSizeInitializer: false);
                }
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"").Append(MetadataKey).Append("\", ")
                    .Append(SymbolDisplay.FormatLiteral(phase + "\n" + payload, true)).Append(")]\n");
                ++count;
            }
        }
        if (count != 0) output.AddSource("ME.BECS.ViewSafety.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    internal static bool IsView(INamedTypeSymbol type, INamedTypeSymbol? view) {
        for (var owner = type; owner != null; owner = owner.BaseType)
            if (SymbolEqualityComparer.Default.Equals(owner, view)) return true;
        return false;
    }

    private static IMethodSymbol[] Callbacks(INamedTypeSymbol type, string phase, INamedTypeSymbol? view, Compilation compilation) {
        var moduleRole = phase.StartsWith("module:", StringComparison.Ordinal);
        if (moduleRole) phase = phase.Substring(7);
        if (!moduleRole && IsView(type, view)) {
            var slots = view!.GetMembers(phase).OfType<IMethodSymbol>().Where(static method => !method.IsStatic && method.IsVirtual).ToArray();
            if (slots.Length != 1) return Array.Empty<IMethodSymbol>();
            return new[] { MostDerived(type, slots[0]) };
        }
        var contract = compilation.GetTypeByMetadataName("ME.BECS.Views.IView" + phase);
        if (contract == null || !type.AllInterfaces.Contains(contract, SymbolEqualityComparer.Default)) return Array.Empty<IMethodSymbol>();
        return contract.GetMembers(phase).Select(type.FindImplementationForInterfaceMember).OfType<IMethodSymbol>()
            .Select(method => MostDerived(type, method)).ToArray();
    }

    internal static IMethodSymbol MostDerived(INamedTypeSymbol type, IMethodSymbol slot) {
        // Roslyn's interface map can return the inherited implementation rather than
        // its override on this concrete owner. Resolve that virtual slot, not a new method.
        if (!slot.IsVirtual && !slot.IsOverride && !slot.IsAbstract) return slot;
        IMethodSymbol Definition(IMethodSymbol method) {
            while (method.OverriddenMethod != null) method = method.OverriddenMethod;
            return method.OriginalDefinition;
        }
        var definition = Definition(slot);
        for (var owner = type; owner != null; owner = owner.BaseType) {
            foreach (var method in owner.GetMembers(slot.Name).OfType<IMethodSymbol>())
                if (SymbolEqualityComparer.Default.Equals(Definition(method), definition)) return method;
        }
        return slot;
    }
}
