using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorViewsFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ViewsPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG120", "Invalid views publication input", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG121", "Views publication awaits Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor =>
                System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            var compilation = input.Right;
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                var profile = editor ? "Editor" : "Runtime";
                void Fail(string reason) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                    reason + " in " + file.Path + ". No views fragment was published; regenerate inputs and wait for compilation."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) ||
                    document.Owner != compilation.AssemblyName || document.Editor != editor) { Fail("Invalid or duplicate views fragment"); continue; }
                var source = new StringBuilder("// <auto-generated/>\n");
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    if (compilation.GetTypeByMetadataName("ME.BECS.Views.BootstrapViews") == null ||
                        compilation.GetTypeByMetadataName("UnityEngine.Scripting.PreserveAttribute") == null ||
                        compilation.GetTypeByMetadataName(editor ? "UnityEditor.InitializeOnLoadMethodAttribute" : "UnityEngine.RuntimeInitializeOnLoadMethodAttribute") == null) {
                        Fail("The selected views owner requires Views and initialization references"); continue;
                    }
                    var resolver = new InputManifestTypes(compilation, output.CancellationToken);
                    var views = new ViewTypeInputEmitter(compilation, output.CancellationToken);
                    var entries = document.Entries.Select(value => { Format.TryEntry(value.Value, out var entry); return (value.Key, Entry: entry); }).ToArray();
                    var viewCount = entries.Count(entry => entry.Entry.Phase == "ViewType");
                    if (viewCount != 0 && !views.Read(new[] { "view-type-schema", "0", Envelope.Encode("v1\n" + viewCount.ToString(CultureInfo.InvariantCulture)) },
                            resolver, compilation, out var schemaError)) { Fail(schemaError); continue; }
                    var methods = new StringBuilder();
                    var valid = true;
                    foreach (var item in entries) {
                        output.CancellationToken.ThrowIfCancellationRequested();
                        var entry = item.Entry;
                        var type = resolver.ResolveDefinition(entry.Component, out var gap);
                        var contract = compilation.GetTypeByMetadataName(entry.Phase == "Component" ? "ME.BECS.IComponentBase" :
                            entry.Phase == "ModuleTracker" ? "ME.BECS.Views.IViewModule" : "ME.BECS.Views.IView");
                        if (type == null || type.IsAbstract || type.IsRefLikeType || MethodSummaryType.From(type).IsOpen || contract == null ||
                            !type.AllInterfaces.Contains(contract, SymbolEqualityComparer.Default) || !compilation.IsSymbolAccessibleWithin(type, compilation.Assembly) ||
                            entry.Phase == "Component" && !type.IsUnmanagedType) {
                            Fail("Cannot publish " + entry.Component + " (" + (gap ?? "invalid or inaccessible " + entry.Phase) + ")"); valid = false; break;
                        }
                        methods.Append("[global::UnityEngine.Scripting.PreserveAttribute] private static uint Register_").Append(item.Key.ToString(CultureInfo.InvariantCulture))
                            .Append("(global::ME.BECS.ViewsTracker.ViewInfo info) {\n");
                        var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        if (entry.Phase == "Component") {
                            methods.Append("global::ME.BECS.StaticTypes<").Append(name).Append(">.TrackVersion(); return global::ME.BECS.StaticTypes<")
                                .Append(name).Append(">.trackerIndex;\n");
                        } else {
                            if (entry.Phase == "ViewType") {
                                if (!views.Read(new[] { "view-type", views.Types.Count.ToString(CultureInfo.InvariantCulture), Envelope.Encode(entry.Component) },
                                        resolver, compilation, out var error)) { Fail(error); valid = false; break; }
                                ViewTypeInputEmitter.AppendRegistration(methods, type, views.Types[views.Types.Count - 1].Flags);
                            } else methods.Append("global::ME.BECS.ViewsTracker.").Append(entry.Phase == "ModuleTracker" ? "TrackViewModule" : "TrackView")
                                .Append('<').Append(name).Append(">(info);\n");
                            methods.Append("return 0u;\n");
                        }
                        methods.Append("}\n");
                    }
                    if (!valid) continue;
                    source.Append("namespace ME.BECS.SourceGenerated {\n[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static class ViewsFragment_")
                        .Append(profile).Append(" {\nprivate static readonly int[] Ordinals = new int[] { ")
                        .Append(string.Join(",", document.Entries.Select(entry => entry.Key.ToString(CultureInfo.InvariantCulture)))).Append(" };\n")
                        .Append("private static readonly global::ME.BECS.Views.ViewRegistrationCallback[] Callbacks = new global::ME.BECS.Views.ViewRegistrationCallback[] {\n")
                        .Append(string.Join(",", document.Entries.Select(entry => "Register_" + entry.Key.ToString(CultureInfo.InvariantCulture)))).Append("\n};\n").Append(methods)
                        .Append(editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                            "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
                        .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() => global::ME.BECS.Views.BootstrapViews.InstallFragment(")
                        .Append(SymbolDisplay.FormatLiteral(document.Plan, true)).Append(", ")
                        .Append(SymbolDisplay.FormatLiteral(document.Owner, true)).Append(", ").Append(document.Count.ToString(CultureInfo.InvariantCulture))
                        .Append(", Ordinals, Callbacks, editor: ").Append(editor ? "true" : "false").Append(");\n} }\n");
                }
                output.AddSource("ME.BECS.ViewsFragment." + profile + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
