using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Format = ME.BECS.CodeGeneration.SourceGeneratorViewSelectionFragmentFormat;
using Envelope = ME.BECS.CodeGeneration.SourceGeneratorSystemFragmentFormat;

namespace ME.BECS.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ViewSelectionPublicationGenerator : IIncrementalGenerator {
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor("BECSG132", "Invalid Views dependency publication", "{0}", "ME.BECS", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Recovery = new DiagnosticDescriptor("BECSG133", "Views dependencies await Editor input recovery", "{0}", "ME.BECS", DiagnosticSeverity.Warning, true);
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var files = context.AdditionalTextsProvider.Where(static file => Format.IsInput(file.Path))
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? ""))
            .Where(static input => new[] { false, true }.Any(editor => System.IO.Path.GetFileName(input.Left.Path.Replace('\\', '/')) == Format.FileName(input.Right, editor)))
            .Select(static (input, cancellation) => (input.Left.Path, Content: input.Left.GetText(cancellation)?.ToString())).Collect();
        context.RegisterSourceOutput(files.Combine(context.CompilationProvider), static (output, input) => {
            // Private QueryWith fields on imported aspects participate in explicit tracking.
            var compilation = input.Right.WithOptions(input.Right.Options.WithMetadataImportOptions(MetadataImportOptions.All));
            var inEditor = compilation.SyntaxTrees.Any(tree => tree.Options.PreprocessorSymbolNames.Contains("UNITY_EDITOR"));
            var seen = new HashSet<bool>();
            foreach (var file in input.Left) {
                var editor = System.IO.Path.GetFileName(file.Path.Replace('\\', '/')) == Format.FileName(compilation.AssemblyName!, true);
                if (editor && !inEditor) continue;
                void Fail(string message) => output.ReportDiagnostic(Diagnostic.Create(inEditor ? Recovery : Invalid, Location.None,
                    message + " in " + file.Path + ". No Views dependency plan was published."));
                if (!seen.Add(editor) || !Format.TryParse(file.Content!, out var document) || document.Owner != compilation.AssemblyName || document.Editor != editor) {
                    Fail("Invalid or duplicate Views dependency input"); continue;
                }
                var source = new StringBuilder("// <auto-generated/>\n[assembly: global::System.Reflection.AssemblyMetadataAttribute(")
                    .Append(SymbolDisplay.FormatLiteral(Format.MetadataKey, true)).Append(", ")
                    .Append(SymbolDisplay.FormatLiteral(Envelope.Metadata(document, file.Content!), true)).Append(")]\n");
                if (document.Entries.Length != 0) {
                    var resolver = new InputManifestTypes(compilation, output.CancellationToken);
                    var trackers = new ViewTrackerInputEmitter();
                    var views = new ViewTypeInputEmitter(compilation, output.CancellationToken);
                    var owners = new ViewsRegistrationOwners();
                    var valid = true;
                    foreach (var row in Format.Rows(document.Entries[0].Value)) {
                        output.CancellationToken.ThrowIfCancellationRequested();
                        var fields = row.Split('\t');
                        var error = "Invalid Views registration owners";
                        valid = ViewTrackerInputEmitter.IsRecord(fields[0]) ? trackers.Read(fields, resolver, compilation, out error) :
                            ViewTypeInputEmitter.IsRecord(fields[0]) ? views.Read(fields, resolver, compilation, out error) : owners.Read(fields);
                        if (!valid) { Fail(error); break; }
                    }
                    if (!valid) continue;
                    if (!views.Validate(1, trackers, out var planError) || !trackers.Validate(resolver, compilation, out planError)) { Fail(planError); continue; }
                    if (!owners.Distributed || !owners.Matches(trackers, views)) { Fail("Views owners differ from the compiler-selected tracker/type order"); continue; }
                    trackers.AppendMetadata(source);
                    views.AppendMetadata(source);
                    ViewsInputEmitter.Append(source, owners, trackers, views, editor);
                    source.Append("namespace ME.BECS.SourceGenerated { [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]\ninternal static class ViewSelectionProfile_")
                        .Append(editor ? "Editor" : "Runtime").Append(" {\n")
                        .Append(editor ? "[global::UnityEditor.InitializeOnLoadMethodAttribute]\n" :
                            "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n")
                        .Append("[global::UnityEngine.Scripting.PreserveAttribute]\nprivate static void Publish() => BootstrapViewsSelection.Publish();\n} }\n");
                }
                output.AddSource("ME.BECS.ViewSelectionFragment." + (editor ? "Editor" : "Runtime") + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        });
    }
}
