using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

// A tiny cross-assembly body contract, independent of ECS safety completeness.
// Only compiler-proven no-ops can be suppressed. Consumers must reject missing
// contracts: an extra callback can mutate the provider's shared change tracker.
[Generator(LanguageNames.CSharp)]
public sealed class ViewCallbackBodyGenerator : IIncrementalGenerator {
    internal const string MetadataKey = "ME.BECS.ViewCallbackBody.v1";
    internal static readonly (string Method, string Flag)[] Phases = {
        ("OnInitialize", "Initialize"), ("OnDeInitialize", "DeInitialize"),
        ("OnEnableFromPool", "EnableFromPool"), ("OnDisableToPool", "DisableToPool"),
        ("ApplyState", "ApplyState"), ("OnUpdate", "Update"),
        ("ApplyStateParallel", "ApplyStateParallel"), ("OnUpdateParallel", "UpdateParallel"),
    };

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var records = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is MethodDeclarationSyntax method && Phases.Any(phase => phase.Method == method.Identifier.ValueText),
            static (syntax, cancellation) => {
                if (syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) is not IMethodSymbol method ||
                    method.IsStatic || method.IsAbstract || !method.ReturnsVoid || method.Arity != 0) return null;
                var definition = method;
                while (definition.OverriddenMethod != null) definition = definition.OverriddenMethod;
                var view = syntax.SemanticModel.Compilation.GetTypeByMetadataName("ME.BECS.Views.EntityView");
                if (view == null || !definition.IsVirtual || !SymbolEqualityComparer.Default.Equals(definition.ContainingType, view)) return null;
                var id = method.OriginalDefinition.GetDocumentationCommentId();
                return id == null ? null : "v1\n" + id + "\n" + (IsEmpty(method, syntax.SemanticModel.Compilation, cancellation) ? "empty" : "active");
            }).Where(static record => record != null).Collect();
        context.RegisterSourceOutput(records, static (output, input) => {
            if (input.Length == 0) return;
            var source = new StringBuilder("// <auto-generated/>\n");
            foreach (var record in input.Distinct(StringComparer.Ordinal).OrderBy(static row => row, StringComparer.Ordinal))
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"").Append(MetadataKey).Append("\", ")
                    .Append(SymbolDisplay.FormatLiteral(record!, true)).Append(")]\n");
            output.AddSource("ME.BECS.ViewCallbackBodies.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }

    internal static bool IsEmpty(IMethodSymbol method, Compilation compilation, System.Threading.CancellationToken cancellation) {
        // Even an empty async void method initializes an async state machine.
        if (method.IsAsync || method.IsExtern || method.IsAbstract || !method.ReturnsVoid) return false;
        var declarations = method.DeclaringSyntaxReferences;
        if (declarations.Length != 1 || declarations[0].GetSyntax(cancellation) is not MethodDeclarationSyntax declaration) return false;
        var model = compilation.GetSemanticModel(declaration.SyntaxTree);
        if (model.GetOperation(declaration, cancellation) is not IMethodBodyOperation body) return false;
        var block = body.BlockBody ?? body.ExpressionBody;
        if (block == null) return false;
        bool ConstantCondition(IOperation condition, out bool value) {
            value = false;
            // Only constant leaves. Do not discard evaluation merely because an
            // optimizer can infer a result from an expression with side effects.
            if (condition is IParenthesizedOperation parenthesized) return ConstantCondition(parenthesized.Operand, out value);
            if (condition is not ILiteralOperation && condition is not IFieldReferenceOperation { Field: { IsConst: true } }) return false;
            if (!condition.ConstantValue.HasValue || condition.ConstantValue.Value is not bool constant) return false;
            value = constant;
            return true;
        }
        bool Empty(IOperation operation) {
            cancellation.ThrowIfCancellationRequested();
            return operation switch {
                IBlockOperation body => body.Operations.All(Empty),
                IEmptyOperation => true,
                IReturnOperation { ReturnedValue: null } => true,
                ILocalFunctionOperation => true, // A declaration does not invoke the function.
                IExpressionStatementOperation { Operation: IInvocationOperation invocation } => Omitted(invocation, cancellation),
                IConditionalOperation conditional when ConstantCondition(conditional.Condition, out var condition) =>
                    condition ? Empty(conditional.WhenTrue) : conditional.WhenFalse == null || Empty(conditional.WhenFalse),
                _ => false,
            };
        }
        // Deliberately not a purity optimizer: calls (including base calls), argument
        // evaluation, assignments, allocations and unknown operations stay enabled.
        return Empty(block);
    }

    private static bool Omitted(IInvocationOperation invocation, System.Threading.CancellationToken cancellation) {
        var method = invocation.TargetMethod;
        if (method.IsPartialDefinition && method.PartialImplementationPart == null && method.ReturnsVoid) return true;
        var symbols = new HashSet<string>(StringComparer.Ordinal);
        for (var current = method; current != null; current = current.OverriddenMethod)
            foreach (var attribute in current.GetAttributes())
                if (attribute.AttributeClass?.ToDisplayString() == "System.Diagnostics.ConditionalAttribute" &&
                    attribute.ConstructorArguments.Length == 1 && attribute.ConstructorArguments[0].Value is string symbol) symbols.Add(symbol);
        if (symbols.Count == 0) return false;
        var defined = new HashSet<string>(((CSharpParseOptions)invocation.Syntax.SyntaxTree.Options).PreprocessorSymbolNames, StringComparer.Ordinal);
        foreach (var trivia in invocation.Syntax.SyntaxTree.GetRoot(cancellation).DescendantTrivia(descendIntoTrivia: true)) {
            if (trivia.SpanStart >= invocation.Syntax.SpanStart) break;
            if (!trivia.HasStructure) continue;
            if (trivia.GetStructure() is DefineDirectiveTriviaSyntax define && define.IsActive) defined.Add(define.Name.ValueText);
            else if (trivia.GetStructure() is UndefDirectiveTriviaSyntax undef && undef.IsActive) defined.Remove(undef.Name.ValueText);
        }
        // Conditional/omitted partial calls suppress receiver and argument
        // evaluation too. Merely declaring an unused local function does as well.
        return !symbols.Any(defined.Contains);
    }
}
