using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace ME.BECS.SourceGenerator;

internal static class ViewSafetySummary {
    internal const string MetadataKey = "ME.BECS.ViewSafety.v1";

    internal static void Emit(SourceProductionContext output, Compilation compilation,
        IReadOnlyDictionary<(string Assembly, string Id), MethodSummaryGraph.Summary> methods,
        ISet<(string Assembly, string Id)> conflicts) {
        var view = compilation.GetTypeByMetadataName("ME.BECS.Views.IView");
        var module = compilation.GetTypeByMetadataName("ME.BECS.Views.IViewModule");
        if (view == null && module == null) return;
        IEnumerable<INamedTypeSymbol> Types(INamespaceOrTypeSymbol owner) {
            foreach (var member in owner.GetMembers()) {
                if (member is INamespaceSymbol space) {
                    foreach (var item in Types(space)) yield return item;
                } else if (member is INamedTypeSymbol type) {
                    yield return type;
                    foreach (var item in Types(type)) yield return item;
                }
            }
        }
        var source = new StringBuilder("// <auto-generated/>\n");
        var count = 0;
        var decoded = new Dictionary<string, MethodSummaryType?>(StringComparer.Ordinal);
        MethodSummaryType? Decode(string token) {
            if (!decoded.TryGetValue(token, out var value)) {
                if (!MethodSummaryType.TryDecode(token, out value)) value = null;
                decoded.Add(token, value);
            }
            return value;
        }
        foreach (var type in Types(compilation.Assembly.GlobalNamespace).OrderBy(static t => t.ToDisplayString(), StringComparer.Ordinal)) {
            if (type.IsAbstract || MethodSummaryType.From(type).IsOpen ||
                !type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, view) || SymbolEqualityComparer.Default.Equals(i, module))) continue;
            var name = string.Join("+", MethodSummaryType.TypeOwners(type).Select(static owner => owner.MetadataName));
            if (!type.ContainingNamespace.IsGlobalNamespace) name = type.ContainingNamespace.ToDisplayString() + "." + name;
            foreach (var phase in new[] { "ApplyState", "ApplyStateParallel" }) {
                output.CancellationToken.ThrowIfCancellationRequested();
                // Match the most-derived named implementation. Do not union hidden base
                // implementations: base calls, when executed, are already summary edges.
                IMethodSymbol[] candidates = Array.Empty<IMethodSymbol>();
                for (var owner = type; owner != null && candidates.Length == 0; owner = owner.BaseType)
                    candidates = owner.GetMembers(phase).OfType<IMethodSymbol>().Where(static method => !method.IsStatic && method.MethodKind == MethodKind.Ordinary).ToArray();
                if (candidates.Length == 0) continue; // No callback, same as the discovery feeder.
                string payload;
                var method = candidates[0];
                var id = MethodSummaryIdentity.Get(method);
                var assembly = method.ContainingAssembly.Identity.ToString();
                if (candidates.Length != 1 || method.Arity != 0 || method.IsAbstract || id == null ||
                    !methods.TryGetValue((assembly, id), out var summary)) {
                    payload = name + "\n" + (id ?? "") + "\n1\nG\tViewCallbackUnavailableOrAmbiguous";
                } else {
                    var root = new MethodSummaryGraph.Summary {
                        Id = summary.Id, Environment = summary.Environment, Unresolved = summary.Unresolved,
                        Flags = summary.Flags.Where(static flag => !flag.StartsWith("job-type=", StringComparison.Ordinal)).Concat(new[] { "job-type=" + name }).ToArray(),
                        RootArguments = MethodSummaryType.From(method.ContainingType).Arguments,
                    };
                    root.Operations.AddRange(summary.Operations);
                    if (root.RootArguments.Length != root.Environment.Length) {
                        payload = name + "\n" + id + "\n1\nG\tViewCallbackGenericContextUnavailable";
                    } else payload = JobSafetySummary.Analyze(output, compilation, assembly, root, methods, conflicts, Decode, emitSizeInitializer: false);
                }
                source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(\"").Append(MetadataKey).Append("\", ")
                    .Append(SymbolDisplay.FormatLiteral(phase + "\n" + payload, true)).Append(")]\n");
                ++count;
            }
        }
        if (count != 0) output.AddSource("ME.BECS.ViewSafety.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
