[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.BurstHelper.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.BurstHelper.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.Transforms")]