[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.Gen.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.Gen.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("ME.BECS.Transforms")]